// Code generated by MockGen. DO NOT EDIT.
// Source: internal/core/ports/services_ports.go
//
// Generated by this command:
//
//	mockgen -source=internal/core/ports/services_ports.go -destination test/mock/services.go
//

// Package mock_ports is a generated GoMock package.
package mock_ports

import (
	context "context"
	reflect "reflect"
	time "time"

	fiber "github.com/gofiber/fiber/v2"
	domain "github.com/highcard-dev/daemon/internal/core/domain"
	ports "github.com/highcard-dev/daemon/internal/core/ports"
	v1 "github.com/opencontainers/image-spec/specs-go/v1"
	gomock "go.uber.org/mock/gomock"
	remote "oras.land/oras-go/v2/registry/remote"
)

// MockAuthorizerServiceInterface is a mock of AuthorizerServiceInterface interface.
type MockAuthorizerServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAuthorizerServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockAuthorizerServiceInterfaceMockRecorder is the mock recorder for MockAuthorizerServiceInterface.
type MockAuthorizerServiceInterfaceMockRecorder struct {
	mock *MockAuthorizerServiceInterface
}

// NewMockAuthorizerServiceInterface creates a new mock instance.
func NewMockAuthorizerServiceInterface(ctrl *gomock.Controller) *MockAuthorizerServiceInterface {
	mock := &MockAuthorizerServiceInterface{ctrl: ctrl}
	mock.recorder = &MockAuthorizerServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthorizerServiceInterface) EXPECT() *MockAuthorizerServiceInterfaceMockRecorder {
	return m.recorder
}

// CheckHeader mocks base method.
func (m *MockAuthorizerServiceInterface) CheckHeader(r *fiber.Ctx) (*ports.AuthContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHeader", r)
	ret0, _ := ret[0].(*ports.AuthContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckHeader indicates an expected call of CheckHeader.
func (mr *MockAuthorizerServiceInterfaceMockRecorder) CheckHeader(r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHeader", reflect.TypeOf((*MockAuthorizerServiceInterface)(nil).CheckHeader), r)
}

// CheckQuery mocks base method.
func (m *MockAuthorizerServiceInterface) CheckQuery(runtimeID string, token string) (*ports.AuthContext, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckQuery", runtimeID, token)
	ret0, _ := ret[0].(*ports.AuthContext)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckQuery indicates an expected call of CheckQuery.
func (mr *MockAuthorizerServiceInterfaceMockRecorder) CheckQuery(runtimeID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckQuery", reflect.TypeOf((*MockAuthorizerServiceInterface)(nil).CheckQuery), runtimeID, token)
}

// GenerateQueryToken mocks base method.
func (m *MockAuthorizerServiceInterface) GenerateQueryToken(runtimeID string, ownerID string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateQueryToken", runtimeID, ownerID)
	ret0, _ := ret[0].(string)
	return ret0
}

// GenerateQueryToken indicates an expected call of GenerateQueryToken.
func (mr *MockAuthorizerServiceInterfaceMockRecorder) GenerateQueryToken(runtimeID, ownerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateQueryToken", reflect.TypeOf((*MockAuthorizerServiceInterface)(nil).GenerateQueryToken), runtimeID, ownerID)
}

// MockScrollServiceInterface is a mock of ScrollServiceInterface interface.
type MockScrollServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockScrollServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockScrollServiceInterfaceMockRecorder is the mock recorder for MockScrollServiceInterface.
type MockScrollServiceInterfaceMockRecorder struct {
	mock *MockScrollServiceInterface
}

// NewMockScrollServiceInterface creates a new mock instance.
func NewMockScrollServiceInterface(ctrl *gomock.Controller) *MockScrollServiceInterface {
	mock := &MockScrollServiceInterface{ctrl: ctrl}
	mock.recorder = &MockScrollServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScrollServiceInterface) EXPECT() *MockScrollServiceInterfaceMockRecorder {
	return m.recorder
}

// GetCommand mocks base method.
func (m *MockScrollServiceInterface) GetCommand(cmd string) (*domain.CommandInstructionSet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommand", cmd)
	ret0, _ := ret[0].(*domain.CommandInstructionSet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommand indicates an expected call of GetCommand.
func (mr *MockScrollServiceInterfaceMockRecorder) GetCommand(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommand", reflect.TypeOf((*MockScrollServiceInterface)(nil).GetCommand), cmd)
}

// GetCurrent mocks base method.
func (m *MockScrollServiceInterface) GetCurrent() *domain.Scroll {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrent")
	ret0, _ := ret[0].(*domain.Scroll)
	return ret0
}

// GetCurrent indicates an expected call of GetCurrent.
func (mr *MockScrollServiceInterfaceMockRecorder) GetCurrent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrent", reflect.TypeOf((*MockScrollServiceInterface)(nil).GetCurrent))
}

// GetCwd mocks base method.
func (m *MockScrollServiceInterface) GetCwd() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCwd")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetCwd indicates an expected call of GetCwd.
func (mr *MockScrollServiceInterfaceMockRecorder) GetCwd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCwd", reflect.TypeOf((*MockScrollServiceInterface)(nil).GetCwd))
}

// GetDir mocks base method.
func (m *MockScrollServiceInterface) GetDir() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDir")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDir indicates an expected call of GetDir.
func (mr *MockScrollServiceInterfaceMockRecorder) GetDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDir", reflect.TypeOf((*MockScrollServiceInterface)(nil).GetDir))
}

// GetFile mocks base method.
func (m *MockScrollServiceInterface) GetFile() *domain.File {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFile")
	ret0, _ := ret[0].(*domain.File)
	return ret0
}

// GetFile indicates an expected call of GetFile.
func (mr *MockScrollServiceInterfaceMockRecorder) GetFile() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFile", reflect.TypeOf((*MockScrollServiceInterface)(nil).GetFile))
}

// MockProcedureLauchnerInterface is a mock of ProcedureLauchnerInterface interface.
type MockProcedureLauchnerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProcedureLauchnerInterfaceMockRecorder
	isgomock struct{}
}

// MockProcedureLauchnerInterfaceMockRecorder is the mock recorder for MockProcedureLauchnerInterface.
type MockProcedureLauchnerInterfaceMockRecorder struct {
	mock *MockProcedureLauchnerInterface
}

// NewMockProcedureLauchnerInterface creates a new mock instance.
func NewMockProcedureLauchnerInterface(ctrl *gomock.Controller) *MockProcedureLauchnerInterface {
	mock := &MockProcedureLauchnerInterface{ctrl: ctrl}
	mock.recorder = &MockProcedureLauchnerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcedureLauchnerInterface) EXPECT() *MockProcedureLauchnerInterfaceMockRecorder {
	return m.recorder
}

// GetProcedureStatuses mocks base method.
func (m *MockProcedureLauchnerInterface) GetProcedureStatuses() map[string]domain.ScrollLockStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProcedureStatuses")
	ret0, _ := ret[0].(map[string]domain.ScrollLockStatus)
	return ret0
}

// GetProcedureStatuses indicates an expected call of GetProcedureStatuses.
func (mr *MockProcedureLauchnerInterfaceMockRecorder) GetProcedureStatuses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProcedureStatuses", reflect.TypeOf((*MockProcedureLauchnerInterface)(nil).GetProcedureStatuses))
}

// Run mocks base method.
func (m *MockProcedureLauchnerInterface) Run(cmd string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockProcedureLauchnerInterfaceMockRecorder) Run(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockProcedureLauchnerInterface)(nil).Run), cmd)
}

// MockLogManagerInterface is a mock of LogManagerInterface interface.
type MockLogManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockLogManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockLogManagerInterfaceMockRecorder is the mock recorder for MockLogManagerInterface.
type MockLogManagerInterfaceMockRecorder struct {
	mock *MockLogManagerInterface
}

// NewMockLogManagerInterface creates a new mock instance.
func NewMockLogManagerInterface(ctrl *gomock.Controller) *MockLogManagerInterface {
	mock := &MockLogManagerInterface{ctrl: ctrl}
	mock.recorder = &MockLogManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogManagerInterface) EXPECT() *MockLogManagerInterfaceMockRecorder {
	return m.recorder
}

// AddLine mocks base method.
func (m *MockLogManagerInterface) AddLine(stream string, sc []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddLine", stream, sc)
}

// AddLine indicates an expected call of AddLine.
func (mr *MockLogManagerInterfaceMockRecorder) AddLine(stream, sc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddLine", reflect.TypeOf((*MockLogManagerInterface)(nil).AddLine), stream, sc)
}

// GetStreams mocks base method.
func (m *MockLogManagerInterface) GetStreams() map[string]*domain.Log {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreams")
	ret0, _ := ret[0].(map[string]*domain.Log)
	return ret0
}

// GetStreams indicates an expected call of GetStreams.
func (mr *MockLogManagerInterfaceMockRecorder) GetStreams() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreams", reflect.TypeOf((*MockLogManagerInterface)(nil).GetStreams))
}

// MockRuntimeBackendInterface is a mock of RuntimeBackendInterface interface.
type MockRuntimeBackendInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeBackendInterfaceMockRecorder
	isgomock struct{}
}

// MockRuntimeBackendInterfaceMockRecorder is the mock recorder for MockRuntimeBackendInterface.
type MockRuntimeBackendInterfaceMockRecorder struct {
	mock *MockRuntimeBackendInterface
}

// NewMockRuntimeBackendInterface creates a new mock instance.
func NewMockRuntimeBackendInterface(ctrl *gomock.Controller) *MockRuntimeBackendInterface {
	mock := &MockRuntimeBackendInterface{ctrl: ctrl}
	mock.recorder = &MockRuntimeBackendInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeBackendInterface) EXPECT() *MockRuntimeBackendInterfaceMockRecorder {
	return m.recorder
}

// Attach mocks base method.
func (m *MockRuntimeBackendInterface) Attach(commandName, data string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Attach", commandName, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Attach indicates an expected call of Attach.
func (mr *MockRuntimeBackendInterfaceMockRecorder) Attach(commandName, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Attach", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).Attach), commandName, data)
}

// BackupRuntime mocks base method.
func (m *MockRuntimeBackendInterface) BackupRuntime(ctx context.Context, root, artifact string, registryCredentials []domain.RegistryCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BackupRuntime", ctx, root, artifact, registryCredentials)
	ret0, _ := ret[0].(error)
	return ret0
}

// BackupRuntime indicates an expected call of BackupRuntime.
func (mr *MockRuntimeBackendInterfaceMockRecorder) BackupRuntime(ctx, root, artifact, registryCredentials any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BackupRuntime", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).BackupRuntime), ctx, root, artifact, registryCredentials)
}

// DeleteRuntime mocks base method.
func (m *MockRuntimeBackendInterface) DeleteRuntime(root string, purgeData bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRuntime", root, purgeData)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRuntime indicates an expected call of DeleteRuntime.
func (mr *MockRuntimeBackendInterfaceMockRecorder) DeleteRuntime(root, purgeData any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRuntime", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).DeleteRuntime), root, purgeData)
}

// ExpectedPorts mocks base method.
func (m *MockRuntimeBackendInterface) ExpectedPorts(root string, commands map[string]*domain.CommandInstructionSet, globalPorts []domain.Port) ([]domain.RuntimePortStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExpectedPorts", root, commands, globalPorts)
	ret0, _ := ret[0].([]domain.RuntimePortStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExpectedPorts indicates an expected call of ExpectedPorts.
func (mr *MockRuntimeBackendInterfaceMockRecorder) ExpectedPorts(root, commands, globalPorts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExpectedPorts", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).ExpectedPorts), root, commands, globalPorts)
}

// Name mocks base method.
func (m *MockRuntimeBackendInterface) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockRuntimeBackendInterfaceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).Name))
}

// StartDev mocks base method.
func (m *MockRuntimeBackendInterface) StartDev(ctx context.Context, action ports.RuntimeDevAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartDev", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartDev indicates an expected call of StartDev.
func (mr *MockRuntimeBackendInterfaceMockRecorder) StartDev(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartDev", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).StartDev), ctx, action)
}

// ReadScrollFile mocks base method.
func (m *MockRuntimeBackendInterface) ReadScrollFile(root string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadScrollFile", root)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadScrollFile indicates an expected call of ReadScrollFile.
func (mr *MockRuntimeBackendInterfaceMockRecorder) ReadScrollFile(root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadScrollFile", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).ReadScrollFile), root)
}

// RestoreRuntime mocks base method.
func (m *MockRuntimeBackendInterface) RestoreRuntime(ctx context.Context, root, artifact string, registryCredentials []domain.RegistryCredential) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreRuntime", ctx, root, artifact, registryCredentials)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreRuntime indicates an expected call of RestoreRuntime.
func (mr *MockRuntimeBackendInterfaceMockRecorder) RestoreRuntime(ctx, root, artifact, registryCredentials any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreRuntime", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).RestoreRuntime), ctx, root, artifact, registryCredentials)
}

// RoutingTargets mocks base method.
func (m *MockRuntimeBackendInterface) RoutingTargets(root string, commands map[string]*domain.CommandInstructionSet, globalPorts []domain.Port) ([]domain.RuntimeRoutingTarget, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RoutingTargets", root, commands, globalPorts)
	ret0, _ := ret[0].([]domain.RuntimeRoutingTarget)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RoutingTargets indicates an expected call of RoutingTargets.
func (mr *MockRuntimeBackendInterfaceMockRecorder) RoutingTargets(root, commands, globalPorts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RoutingTargets", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).RoutingTargets), root, commands, globalPorts)
}

// RunCommand mocks base method.
func (m *MockRuntimeBackendInterface) RunCommand(command ports.RuntimeCommand) (*int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunCommand", command)
	ret0, _ := ret[0].(*int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunCommand indicates an expected call of RunCommand.
func (mr *MockRuntimeBackendInterfaceMockRecorder) RunCommand(command any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunCommand", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).RunCommand), command)
}

// Signal mocks base method.
func (m *MockRuntimeBackendInterface) Signal(commandName, target, signal, root string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Signal", commandName, target, signal, root)
	ret0, _ := ret[0].(error)
	return ret0
}

// Signal indicates an expected call of Signal.
func (mr *MockRuntimeBackendInterfaceMockRecorder) Signal(commandName, target, signal, root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Signal", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).Signal), commandName, target, signal, root)
}

// SpawnPullWorker mocks base method.
func (m *MockRuntimeBackendInterface) SpawnPullWorker(ctx context.Context, action ports.RuntimeWorkerAction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SpawnPullWorker", ctx, action)
	ret0, _ := ret[0].(error)
	return ret0
}

// SpawnPullWorker indicates an expected call of SpawnPullWorker.
func (mr *MockRuntimeBackendInterfaceMockRecorder) SpawnPullWorker(ctx, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SpawnPullWorker", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).SpawnPullWorker), ctx, action)
}

// StopRuntime mocks base method.
func (m *MockRuntimeBackendInterface) StopRuntime(root string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopRuntime", root)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopRuntime indicates an expected call of StopRuntime.
func (mr *MockRuntimeBackendInterfaceMockRecorder) StopRuntime(root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopRuntime", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).StopRuntime), root)
}

// StopDev mocks base method.
func (m *MockRuntimeBackendInterface) StopDev(ctx context.Context, root string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopDev", ctx, root)
	ret0, _ := ret[0].(error)
	return ret0
}

// StopDev indicates an expected call of StopDev.
func (mr *MockRuntimeBackendInterfaceMockRecorder) StopDev(ctx, root any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopDev", reflect.TypeOf((*MockRuntimeBackendInterface)(nil).StopDev), ctx, root)
}

// MockBroadcastChannelInterface is a mock of BroadcastChannelInterface interface.
type MockBroadcastChannelInterface struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcastChannelInterfaceMockRecorder
	isgomock struct{}
}

// MockBroadcastChannelInterfaceMockRecorder is the mock recorder for MockBroadcastChannelInterface.
type MockBroadcastChannelInterfaceMockRecorder struct {
	mock *MockBroadcastChannelInterface
}

// NewMockBroadcastChannelInterface creates a new mock instance.
func NewMockBroadcastChannelInterface(ctrl *gomock.Controller) *MockBroadcastChannelInterface {
	mock := &MockBroadcastChannelInterface{ctrl: ctrl}
	mock.recorder = &MockBroadcastChannelInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcastChannelInterface) EXPECT() *MockBroadcastChannelInterfaceMockRecorder {
	return m.recorder
}

// NewHub mocks base method.
func (m *MockBroadcastChannelInterface) NewHub() *domain.BroadcastChannel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewHub")
	ret0, _ := ret[0].(*domain.BroadcastChannel)
	return ret0
}

// NewHub indicates an expected call of NewHub.
func (mr *MockBroadcastChannelInterfaceMockRecorder) NewHub() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewHub", reflect.TypeOf((*MockBroadcastChannelInterface)(nil).NewHub))
}

// Run mocks base method.
func (m *MockBroadcastChannelInterface) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run.
func (mr *MockBroadcastChannelInterfaceMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockBroadcastChannelInterface)(nil).Run))
}

// MockConsoleManagerInterface is a mock of ConsoleManagerInterface interface.
type MockConsoleManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConsoleManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockConsoleManagerInterfaceMockRecorder is the mock recorder for MockConsoleManagerInterface.
type MockConsoleManagerInterfaceMockRecorder struct {
	mock *MockConsoleManagerInterface
}

// NewMockConsoleManagerInterface creates a new mock instance.
func NewMockConsoleManagerInterface(ctrl *gomock.Controller) *MockConsoleManagerInterface {
	mock := &MockConsoleManagerInterface{ctrl: ctrl}
	mock.recorder = &MockConsoleManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsoleManagerInterface) EXPECT() *MockConsoleManagerInterfaceMockRecorder {
	return m.recorder
}

// AddConsoleWithChannel mocks base method.
func (m *MockConsoleManagerInterface) AddConsoleWithChannel(consoleId string, consoleType domain.ConsoleType, inputMode string, channel chan string) (*domain.Console, chan struct{}) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddConsoleWithChannel", consoleId, consoleType, inputMode, channel)
	ret0, _ := ret[0].(*domain.Console)
	ret1, _ := ret[1].(chan struct{})
	return ret0, ret1
}

// AddConsoleWithChannel indicates an expected call of AddConsoleWithChannel.
func (mr *MockConsoleManagerInterfaceMockRecorder) AddConsoleWithChannel(consoleId, consoleType, inputMode, channel any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddConsoleWithChannel", reflect.TypeOf((*MockConsoleManagerInterface)(nil).AddConsoleWithChannel), consoleId, consoleType, inputMode, channel)
}

// GetConsole mocks base method.
func (m *MockConsoleManagerInterface) GetConsole(consoleId string) *domain.Console {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsole", consoleId)
	ret0, _ := ret[0].(*domain.Console)
	return ret0
}

// GetConsole indicates an expected call of GetConsole.
func (mr *MockConsoleManagerInterfaceMockRecorder) GetConsole(consoleId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsole", reflect.TypeOf((*MockConsoleManagerInterface)(nil).GetConsole), consoleId)
}

// GetConsoles mocks base method.
func (m *MockConsoleManagerInterface) GetConsoles() map[string]*domain.Console {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetConsoles")
	ret0, _ := ret[0].(map[string]*domain.Console)
	return ret0
}

// GetConsoles indicates an expected call of GetConsoles.
func (mr *MockConsoleManagerInterfaceMockRecorder) GetConsoles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetConsoles", reflect.TypeOf((*MockConsoleManagerInterface)(nil).GetConsoles))
}

// MockOciRegistryInterface is a mock of OciRegistryInterface interface.
type MockOciRegistryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOciRegistryInterfaceMockRecorder
	isgomock struct{}
}

// MockOciRegistryInterfaceMockRecorder is the mock recorder for MockOciRegistryInterface.
type MockOciRegistryInterfaceMockRecorder struct {
	mock *MockOciRegistryInterface
}

// NewMockOciRegistryInterface creates a new mock instance.
func NewMockOciRegistryInterface(ctrl *gomock.Controller) *MockOciRegistryInterface {
	mock := &MockOciRegistryInterface{ctrl: ctrl}
	mock.recorder = &MockOciRegistryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOciRegistryInterface) EXPECT() *MockOciRegistryInterfaceMockRecorder {
	return m.recorder
}

// CanUpdateTag mocks base method.
func (m *MockOciRegistryInterface) CanUpdateTag(descriptor v1.Descriptor, folder, tag string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanUpdateTag", descriptor, folder, tag)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CanUpdateTag indicates an expected call of CanUpdateTag.
func (mr *MockOciRegistryInterfaceMockRecorder) CanUpdateTag(descriptor, folder, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanUpdateTag", reflect.TypeOf((*MockOciRegistryInterface)(nil).CanUpdateTag), descriptor, folder, tag)
}

// FetchFile mocks base method.
func (m *MockOciRegistryInterface) FetchFile(artifact, filePath string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchFile", artifact, filePath)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchFile indicates an expected call of FetchFile.
func (mr *MockOciRegistryInterfaceMockRecorder) FetchFile(artifact, filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchFile", reflect.TypeOf((*MockOciRegistryInterface)(nil).FetchFile), artifact, filePath)
}

// GetRepo mocks base method.
func (m *MockOciRegistryInterface) GetRepo(repoUrl string) (*remote.Repository, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRepo", repoUrl)
	ret0, _ := ret[0].(*remote.Repository)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRepo indicates an expected call of GetRepo.
func (mr *MockOciRegistryInterfaceMockRecorder) GetRepo(repoUrl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRepo", reflect.TypeOf((*MockOciRegistryInterface)(nil).GetRepo), repoUrl)
}

// Pull mocks base method.
func (m *MockOciRegistryInterface) Pull(dir, artifact string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", dir, artifact)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pull indicates an expected call of Pull.
func (mr *MockOciRegistryInterfaceMockRecorder) Pull(dir, artifact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockOciRegistryInterface)(nil).Pull), dir, artifact)
}

// PullSelective mocks base method.
func (m *MockOciRegistryInterface) PullSelective(dir, artifact string, includeData bool, progress *domain.SnapshotProgress) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PullSelective", dir, artifact, includeData, progress)
	ret0, _ := ret[0].(error)
	return ret0
}

// PullSelective indicates an expected call of PullSelective.
func (mr *MockOciRegistryInterfaceMockRecorder) PullSelective(dir, artifact, includeData, progress any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PullSelective", reflect.TypeOf((*MockOciRegistryInterface)(nil).PullSelective), dir, artifact, includeData, progress)
}

// Push mocks base method.
func (m *MockOciRegistryInterface) Push(folder, repo, tag string, overrides map[string]string, packMeta bool, scrollFile *domain.File) (v1.Descriptor, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", folder, repo, tag, overrides, packMeta, scrollFile)
	ret0, _ := ret[0].(v1.Descriptor)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Push indicates an expected call of Push.
func (mr *MockOciRegistryInterfaceMockRecorder) Push(folder, repo, tag, overrides, packMeta, scrollFile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockOciRegistryInterface)(nil).Push), folder, repo, tag, overrides, packMeta, scrollFile)
}

// ResolveDigest mocks base method.
func (m *MockOciRegistryInterface) ResolveDigest(artifact string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveDigest", artifact)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveDigest indicates an expected call of ResolveDigest.
func (mr *MockOciRegistryInterfaceMockRecorder) ResolveDigest(artifact any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveDigest", reflect.TypeOf((*MockOciRegistryInterface)(nil).ResolveDigest), artifact)
}

// MockQueueManagerInterface is a mock of QueueManagerInterface interface.
type MockQueueManagerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockQueueManagerInterfaceMockRecorder
	isgomock struct{}
}

// MockQueueManagerInterfaceMockRecorder is the mock recorder for MockQueueManagerInterface.
type MockQueueManagerInterfaceMockRecorder struct {
	mock *MockQueueManagerInterface
}

// NewMockQueueManagerInterface creates a new mock instance.
func NewMockQueueManagerInterface(ctrl *gomock.Controller) *MockQueueManagerInterface {
	mock := &MockQueueManagerInterface{ctrl: ctrl}
	mock.recorder = &MockQueueManagerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueManagerInterface) EXPECT() *MockQueueManagerInterfaceMockRecorder {
	return m.recorder
}

// AddTempItem mocks base method.
func (m *MockQueueManagerInterface) AddTempItem(cmd string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTempItem", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTempItem indicates an expected call of AddTempItem.
func (mr *MockQueueManagerInterfaceMockRecorder) AddTempItem(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTempItem", reflect.TypeOf((*MockQueueManagerInterface)(nil).AddTempItem), cmd)
}

// AddTempItemWithWait mocks base method.
func (m *MockQueueManagerInterface) AddTempItemWithWait(cmd string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTempItemWithWait", cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddTempItemWithWait indicates an expected call of AddTempItemWithWait.
func (mr *MockQueueManagerInterfaceMockRecorder) AddTempItemWithWait(cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTempItemWithWait", reflect.TypeOf((*MockQueueManagerInterface)(nil).AddTempItemWithWait), cmd)
}

// GetQueue mocks base method.
func (m *MockQueueManagerInterface) GetQueue() map[string]domain.ScrollLockStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQueue")
	ret0, _ := ret[0].(map[string]domain.ScrollLockStatus)
	return ret0
}

// GetQueue indicates an expected call of GetQueue.
func (mr *MockQueueManagerInterfaceMockRecorder) GetQueue() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQueue", reflect.TypeOf((*MockQueueManagerInterface)(nil).GetQueue))
}

// MockPortServiceInterface is a mock of PortServiceInterface interface.
type MockPortServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPortServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPortServiceInterfaceMockRecorder is the mock recorder for MockPortServiceInterface.
type MockPortServiceInterfaceMockRecorder struct {
	mock *MockPortServiceInterface
}

// NewMockPortServiceInterface creates a new mock instance.
func NewMockPortServiceInterface(ctrl *gomock.Controller) *MockPortServiceInterface {
	mock := &MockPortServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPortServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortServiceInterface) EXPECT() *MockPortServiceInterfaceMockRecorder {
	return m.recorder
}

// GetPorts mocks base method.
func (m *MockPortServiceInterface) GetPorts() []*domain.AugmentedPort {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPorts")
	ret0, _ := ret[0].([]*domain.AugmentedPort)
	return ret0
}

// GetPorts indicates an expected call of GetPorts.
func (mr *MockPortServiceInterfaceMockRecorder) GetPorts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPorts", reflect.TypeOf((*MockPortServiceInterface)(nil).GetPorts))
}

// MockColdStarterHandlerInterface is a mock of ColdStarterHandlerInterface interface.
type MockColdStarterHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockColdStarterHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockColdStarterHandlerInterfaceMockRecorder is the mock recorder for MockColdStarterHandlerInterface.
type MockColdStarterHandlerInterfaceMockRecorder struct {
	mock *MockColdStarterHandlerInterface
}

// NewMockColdStarterHandlerInterface creates a new mock instance.
func NewMockColdStarterHandlerInterface(ctrl *gomock.Controller) *MockColdStarterHandlerInterface {
	mock := &MockColdStarterHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockColdStarterHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockColdStarterHandlerInterface) EXPECT() *MockColdStarterHandlerInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockColdStarterHandlerInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockColdStarterHandlerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockColdStarterHandlerInterface)(nil).Close))
}

// GetHandler mocks base method.
func (m *MockColdStarterHandlerInterface) GetHandler(funcs map[string]func(...string)) (ports.ColdStarterPacketHandlerInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHandler", funcs)
	ret0, _ := ret[0].(ports.ColdStarterPacketHandlerInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHandler indicates an expected call of GetHandler.
func (mr *MockColdStarterHandlerInterfaceMockRecorder) GetHandler(funcs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHandler", reflect.TypeOf((*MockColdStarterHandlerInterface)(nil).GetHandler), funcs)
}

// SetFinishedAt mocks base method.
func (m *MockColdStarterHandlerInterface) SetFinishedAt(finishedAt *time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFinishedAt", finishedAt)
}

// SetFinishedAt indicates an expected call of SetFinishedAt.
func (mr *MockColdStarterHandlerInterfaceMockRecorder) SetFinishedAt(finishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFinishedAt", reflect.TypeOf((*MockColdStarterHandlerInterface)(nil).SetFinishedAt), finishedAt)
}

// MockColdStarterPacketHandlerInterface is a mock of ColdStarterPacketHandlerInterface interface.
type MockColdStarterPacketHandlerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockColdStarterPacketHandlerInterfaceMockRecorder
	isgomock struct{}
}

// MockColdStarterPacketHandlerInterfaceMockRecorder is the mock recorder for MockColdStarterPacketHandlerInterface.
type MockColdStarterPacketHandlerInterfaceMockRecorder struct {
	mock *MockColdStarterPacketHandlerInterface
}

// NewMockColdStarterPacketHandlerInterface creates a new mock instance.
func NewMockColdStarterPacketHandlerInterface(ctrl *gomock.Controller) *MockColdStarterPacketHandlerInterface {
	mock := &MockColdStarterPacketHandlerInterface{ctrl: ctrl}
	mock.recorder = &MockColdStarterPacketHandlerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockColdStarterPacketHandlerInterface) EXPECT() *MockColdStarterPacketHandlerInterfaceMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockColdStarterPacketHandlerInterface) Handle(data []byte, funcs map[string]func(...string)) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", data, funcs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Handle indicates an expected call of Handle.
func (mr *MockColdStarterPacketHandlerInterfaceMockRecorder) Handle(data, funcs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockColdStarterPacketHandlerInterface)(nil).Handle), data, funcs)
}

// MockColdStarterInterface is a mock of ColdStarterInterface interface.
type MockColdStarterInterface struct {
	ctrl     *gomock.Controller
	recorder *MockColdStarterInterfaceMockRecorder
	isgomock struct{}
}

// MockColdStarterInterfaceMockRecorder is the mock recorder for MockColdStarterInterface.
type MockColdStarterInterfaceMockRecorder struct {
	mock *MockColdStarterInterface
}

// NewMockColdStarterInterface creates a new mock instance.
func NewMockColdStarterInterface(ctrl *gomock.Controller) *MockColdStarterInterface {
	mock := &MockColdStarterInterface{ctrl: ctrl}
	mock.recorder = &MockColdStarterInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockColdStarterInterface) EXPECT() *MockColdStarterInterfaceMockRecorder {
	return m.recorder
}

// Finish mocks base method.
func (m *MockColdStarterInterface) Finish(arg0 *domain.AugmentedPort) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Finish", arg0)
}

// Finish indicates an expected call of Finish.
func (mr *MockColdStarterInterfaceMockRecorder) Finish(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Finish", reflect.TypeOf((*MockColdStarterInterface)(nil).Finish), arg0)
}

// Stop mocks base method.
func (m *MockColdStarterInterface) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockColdStarterInterfaceMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockColdStarterInterface)(nil).Stop))
}

// MockColdStarterServerInterface is a mock of ColdStarterServerInterface interface.
type MockColdStarterServerInterface struct {
	ctrl     *gomock.Controller
	recorder *MockColdStarterServerInterfaceMockRecorder
	isgomock struct{}
}

// MockColdStarterServerInterfaceMockRecorder is the mock recorder for MockColdStarterServerInterface.
type MockColdStarterServerInterfaceMockRecorder struct {
	mock *MockColdStarterServerInterface
}

// NewMockColdStarterServerInterface creates a new mock instance.
func NewMockColdStarterServerInterface(ctrl *gomock.Controller) *MockColdStarterServerInterface {
	mock := &MockColdStarterServerInterface{ctrl: ctrl}
	mock.recorder = &MockColdStarterServerInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockColdStarterServerInterface) EXPECT() *MockColdStarterServerInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockColdStarterServerInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockColdStarterServerInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockColdStarterServerInterface)(nil).Close))
}

// Start mocks base method.
func (m *MockColdStarterServerInterface) Start(port int, onFinish func()) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", port, onFinish)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockColdStarterServerInterfaceMockRecorder) Start(port, onFinish any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockColdStarterServerInterface)(nil).Start), port, onFinish)
}

// MockUiServiceInterface is a mock of UiServiceInterface interface.
type MockUiServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUiServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockUiServiceInterfaceMockRecorder is the mock recorder for MockUiServiceInterface.
type MockUiServiceInterfaceMockRecorder struct {
	mock *MockUiServiceInterface
}

// NewMockUiServiceInterface creates a new mock instance.
func NewMockUiServiceInterface(ctrl *gomock.Controller) *MockUiServiceInterface {
	mock := &MockUiServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUiServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUiServiceInterface) EXPECT() *MockUiServiceInterfaceMockRecorder {
	return m.recorder
}

// GetIndex mocks base method.
func (m *MockUiServiceInterface) GetIndex(filePath string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIndex", filePath)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIndex indicates an expected call of GetIndex.
func (mr *MockUiServiceInterfaceMockRecorder) GetIndex(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIndex", reflect.TypeOf((*MockUiServiceInterface)(nil).GetIndex), filePath)
}

// MockWatchServiceInterface is a mock of WatchServiceInterface interface.
type MockWatchServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockWatchServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockWatchServiceInterfaceMockRecorder is the mock recorder for MockWatchServiceInterface.
type MockWatchServiceInterfaceMockRecorder struct {
	mock *MockWatchServiceInterface
}

// NewMockWatchServiceInterface creates a new mock instance.
func NewMockWatchServiceInterface(ctrl *gomock.Controller) *MockWatchServiceInterface {
	mock := &MockWatchServiceInterface{ctrl: ctrl}
	mock.recorder = &MockWatchServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchServiceInterface) EXPECT() *MockWatchServiceInterfaceMockRecorder {
	return m.recorder
}

// GetWatchedPaths mocks base method.
func (m *MockWatchServiceInterface) GetWatchedPaths() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWatchedPaths")
	ret0, _ := ret[0].([]string)
	return ret0
}

// GetWatchedPaths indicates an expected call of GetWatchedPaths.
func (mr *MockWatchServiceInterfaceMockRecorder) GetWatchedPaths() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWatchedPaths", reflect.TypeOf((*MockWatchServiceInterface)(nil).GetWatchedPaths))
}

// IsWatching mocks base method.
func (m *MockWatchServiceInterface) IsWatching() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsWatching")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsWatching indicates an expected call of IsWatching.
func (mr *MockWatchServiceInterfaceMockRecorder) IsWatching() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsWatching", reflect.TypeOf((*MockWatchServiceInterface)(nil).IsWatching))
}

// SetHotReloadCommands mocks base method.
func (m *MockWatchServiceInterface) SetHotReloadCommands(procs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHotReloadCommands", procs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHotReloadCommands indicates an expected call of SetHotReloadCommands.
func (mr *MockWatchServiceInterfaceMockRecorder) SetHotReloadCommands(procs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHotReloadCommands", reflect.TypeOf((*MockWatchServiceInterface)(nil).SetHotReloadCommands), procs)
}

// StartWatching mocks base method.
func (m *MockWatchServiceInterface) StartWatching(basePath string, paths ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{basePath}
	for _, a := range paths {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "StartWatching", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartWatching indicates an expected call of StartWatching.
func (mr *MockWatchServiceInterfaceMockRecorder) StartWatching(basePath any, paths ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{basePath}, paths...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartWatching", reflect.TypeOf((*MockWatchServiceInterface)(nil).StartWatching), varargs...)
}

// StopWatching mocks base method.
func (m *MockWatchServiceInterface) StopWatching() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopWatching")
	ret0, _ := ret[0].(error)
	return ret0
}

// StopWatching indicates an expected call of StopWatching.
func (mr *MockWatchServiceInterfaceMockRecorder) StopWatching() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopWatching", reflect.TypeOf((*MockWatchServiceInterface)(nil).StopWatching))
}

// Subscribe mocks base method.
func (m *MockWatchServiceInterface) Subscribe() chan *[]byte {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe")
	ret0, _ := ret[0].(chan *[]byte)
	return ret0
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockWatchServiceInterfaceMockRecorder) Subscribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockWatchServiceInterface)(nil).Subscribe))
}

// Trigger mocks base method.
func (m *MockWatchServiceInterface) Trigger() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Trigger")
}

// Trigger indicates an expected call of Trigger.
func (mr *MockWatchServiceInterfaceMockRecorder) Trigger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trigger", reflect.TypeOf((*MockWatchServiceInterface)(nil).Trigger))
}

// Unsubscribe mocks base method.
func (m *MockWatchServiceInterface) Unsubscribe(client chan *[]byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", client)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockWatchServiceInterfaceMockRecorder) Unsubscribe(client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockWatchServiceInterface)(nil).Unsubscribe), client)
}
