{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "druid-cli.fullname" . }}-state
  labels:
    {{- include "druid-cli.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- $storageClass := default .Values.runtime.storageClass .Values.persistence.storageClass }}
  {{- if $storageClass }}
  storageClassName: {{ $storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
{{- end }}
