// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Defines values for RuntimeScrollStatus.
const (
	Created RuntimeScrollStatus = "created"
	Deleted RuntimeScrollStatus = "deleted"
	Error   RuntimeScrollStatus = "error"
	Running RuntimeScrollStatus = "running"
	Stopped RuntimeScrollStatus = "stopped"
)

// ApplyRoutingRequest defines model for ApplyRoutingRequest.
type ApplyRoutingRequest struct {
	Assignments []RuntimeRouteAssignment `json:"assignments"`
}

// CommandStatusMap defines model for CommandStatusMap.
type CommandStatusMap map[string]interface{}

// CreateScrollRequest defines model for CreateScrollRequest.
type CreateScrollRequest struct {
	// Artifact OCI artifact reference or local scroll path
	Artifact string `json:"artifact"`

	// Id Deprecated alias for name. Optional stable runtime id/name. If omitted, the daemon generates an id.
	Id *string `json:"id,omitempty"`

	// Name Optional stable runtime id/name. If omitted, the daemon generates an id; the display name still comes from scroll.yaml.
	Name *string `json:"name,omitempty"`

	// Namespace Kubernetes namespace for runtime resources. Ignored by non-Kubernetes backends.
	Namespace *string `json:"namespace,omitempty"`

	// OwnerId Runtime owner id used for customer-facing route authorization.
	OwnerId             *string               `json:"owner_id,omitempty"`
	RegistryCredentials *[]RegistryCredential `json:"registry_credentials,omitempty"`
}

// DeletedScroll defines model for DeletedScroll.
type DeletedScroll struct {
	Id     string `json:"id"`
	Status string `json:"status"`
}

// EnsureScrollRequest defines model for EnsureScrollRequest.
type EnsureScrollRequest struct {
	Artifact       string  `json:"artifact"`
	ArtifactDigest *string `json:"artifact_digest,omitempty"`
	Id             *string `json:"id,omitempty"`
	Name           *string `json:"name,omitempty"`

	// Namespace Kubernetes namespace for runtime resources. Ignored by non-Kubernetes backends.
	Namespace *string `json:"namespace,omitempty"`

	// OwnerId Runtime owner id used for customer-facing route authorization.
	OwnerId             *string               `json:"owner_id,omitempty"`
	RegistryCredentials *[]RegistryCredential `json:"registry_credentials,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Mode Current health status mode
	Mode string `json:"mode"`

	// Progress Progress percentage for loading operations
	Progress *float32 `json:"progress,omitempty"`

	// StartDate When the daemon started
	StartDate *time.Time `json:"start_date"`
}

// RegistryCredential defines model for RegistryCredential.
type RegistryCredential struct {
	Host     string `json:"host"`
	Password string `json:"password"`
	Username string `json:"username"`
}

// RuntimeArtifactOperationRequest defines model for RuntimeArtifactOperationRequest.
type RuntimeArtifactOperationRequest struct {
	Artifact            string                `json:"artifact"`
	RegistryCredentials *[]RegistryCredential `json:"registry_credentials,omitempty"`
	Restart             *bool                 `json:"restart,omitempty"`
}

// RuntimePortStatus defines model for RuntimePortStatus.
type RuntimePortStatus struct {
	Bound            bool       `json:"bound"`
	HostIp           *string    `json:"host_ip,omitempty"`
	HostPort         *int       `json:"host_port,omitempty"`
	KeepAliveTraffic *string    `json:"keepAliveTraffic,omitempty"`
	LastActivityAt   *time.Time `json:"last_activity_at,omitempty"`
	Name             string     `json:"name"`
	Port             int        `json:"port"`
	Procedure        string     `json:"procedure"`
	Protocol         string     `json:"protocol"`
	RxBytes          *int64     `json:"rx_bytes,omitempty"`
	Source           string     `json:"source"`
	Traffic          bool       `json:"traffic"`
	TrafficBytes     *int64     `json:"traffic_bytes,omitempty"`
	TrafficOk        *bool      `json:"traffic_ok,omitempty"`
	TrafficWindow    *string    `json:"traffic_window,omitempty"`
	TxBytes          *int64     `json:"tx_bytes,omitempty"`
}

// RuntimeRouteAssignment defines model for RuntimeRouteAssignment.
type RuntimeRouteAssignment struct {
	ExternalIp *string `json:"external_ip,omitempty"`
	Host       *string `json:"host,omitempty"`
	Name       *string `json:"name,omitempty"`
	PortName   *string `json:"port_name,omitempty"`
	Protocol   *string `json:"protocol,omitempty"`
	PublicPort *int    `json:"public_port,omitempty"`
	Url        *string `json:"url,omitempty"`
}

// RuntimeRoutingTarget defines model for RuntimeRoutingTarget.
type RuntimeRoutingTarget struct {
	Name        string             `json:"name"`
	Namespace   *string            `json:"namespace,omitempty"`
	Port        int                `json:"port"`
	PortName    string             `json:"port_name"`
	Procedure   string             `json:"procedure"`
	Protocol    string             `json:"protocol"`
	Selector    *map[string]string `json:"selector,omitempty"`
	ServiceName string             `json:"service_name"`
	ServicePort int                `json:"service_port"`
}

// RuntimeScroll defines model for RuntimeScroll.
type RuntimeScroll struct {
	Artifact   string                    `json:"artifact"`
	Commands   *map[string]interface{}   `json:"commands,omitempty"`
	CreatedAt  time.Time                 `json:"created_at"`
	Id         string                    `json:"id"`
	LastError  *string                   `json:"last_error,omitempty"`
	OwnerId    *string                   `json:"owner_id,omitempty"`
	Root       string                    `json:"root"`
	Routing    *[]RuntimeRouteAssignment `json:"routing,omitempty"`
	ScrollName string                    `json:"scroll_name"`
	Status     RuntimeScrollStatus       `json:"status"`
	UpdatedAt  time.Time                 `json:"updated_at"`
}

// RuntimeScrollStatus defines model for RuntimeScroll.Status.
type RuntimeScrollStatus string

// ScrollLogMap defines model for ScrollLogMap.
type ScrollLogMap map[string][]string

// CreateScrollJSONRequestBody defines body for CreateScroll for application/json ContentType.
type CreateScrollJSONRequestBody = CreateScrollRequest

// EnsureScrollJSONRequestBody defines body for EnsureScroll for application/json ContentType.
type EnsureScrollJSONRequestBody = EnsureScrollRequest

// BackupScrollJSONRequestBody defines body for BackupScroll for application/json ContentType.
type BackupScrollJSONRequestBody = RuntimeArtifactOperationRequest

// RestoreScrollJSONRequestBody defines body for RestoreScroll for application/json ContentType.
type RestoreScrollJSONRequestBody = RuntimeArtifactOperationRequest

// ApplyScrollRoutingJSONRequestBody defines body for ApplyScrollRouting for application/json ContentType.
type ApplyScrollRoutingJSONRequestBody = ApplyRoutingRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetHealthAuth request
	GetHealthAuth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListScrolls request
	ListScrolls(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateScrollWithBody request with any body
	CreateScrollWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateScroll(ctx context.Context, body CreateScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EnsureScrollWithBody request with any body
	EnsureScrollWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EnsureScroll(ctx context.Context, body EnsureScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteScroll request
	DeleteScroll(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScroll request
	GetScroll(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// BackupScrollWithBody request with any body
	BackupScrollWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	BackupScroll(ctx context.Context, id string, body BackupScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RunScrollCommand request
	RunScrollCommand(ctx context.Context, id string, command string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScrollConfig request
	GetScrollConfig(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScrollConsoles request
	GetScrollConsoles(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScrollLogs request
	GetScrollLogs(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScrollPorts request
	GetScrollPorts(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScrollProcedures request
	GetScrollProcedures(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScrollQueue request
	GetScrollQueue(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RestoreScrollWithBody request with any body
	RestoreScrollWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RestoreScroll(ctx context.Context, id string, body RestoreScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ApplyScrollRoutingWithBody request with any body
	ApplyScrollRoutingWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ApplyScrollRouting(ctx context.Context, id string, body ApplyScrollRoutingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetScrollRoutingTargets request
	GetScrollRoutingTargets(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StartScroll request
	StartScroll(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StopScroll request
	StopScroll(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetHealthAuth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthAuthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ListScrolls(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListScrollsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateScrollWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateScrollRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateScroll(ctx context.Context, body CreateScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateScrollRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnsureScrollWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnsureScrollRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnsureScroll(ctx context.Context, body EnsureScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnsureScrollRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteScroll(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteScrollRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScroll(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScrollRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BackupScrollWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBackupScrollRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) BackupScroll(ctx context.Context, id string, body BackupScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewBackupScrollRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RunScrollCommand(ctx context.Context, id string, command string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRunScrollCommandRequest(c.Server, id, command)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScrollConfig(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScrollConfigRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScrollConsoles(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScrollConsolesRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScrollLogs(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScrollLogsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScrollPorts(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScrollPortsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScrollProcedures(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScrollProceduresRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScrollQueue(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScrollQueueRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestoreScrollWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestoreScrollRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RestoreScroll(ctx context.Context, id string, body RestoreScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRestoreScrollRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ApplyScrollRoutingWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewApplyScrollRoutingRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ApplyScrollRouting(ctx context.Context, id string, body ApplyScrollRoutingJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewApplyScrollRoutingRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetScrollRoutingTargets(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetScrollRoutingTargetsRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StartScroll(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStartScrollRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StopScroll(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStopScrollRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetHealthAuthRequest generates requests for GetHealthAuth
func NewGetHealthAuthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListScrollsRequest generates requests for ListScrolls
func NewListScrollsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateScrollRequest calls the generic CreateScroll builder with application/json body
func NewCreateScrollRequest(server string, body CreateScrollJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateScrollRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateScrollRequestWithBody generates requests for CreateScroll with any type of body
func NewCreateScrollRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewEnsureScrollRequest calls the generic EnsureScroll builder with application/json body
func NewEnsureScrollRequest(server string, body EnsureScrollJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEnsureScrollRequestWithBody(server, "application/json", bodyReader)
}

// NewEnsureScrollRequestWithBody generates requests for EnsureScroll with any type of body
func NewEnsureScrollRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/ensure")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteScrollRequest generates requests for DeleteScroll
func NewDeleteScrollRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetScrollRequest generates requests for GetScroll
func NewGetScrollRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewBackupScrollRequest calls the generic BackupScroll builder with application/json body
func NewBackupScrollRequest(server string, id string, body BackupScrollJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewBackupScrollRequestWithBody(server, id, "application/json", bodyReader)
}

// NewBackupScrollRequestWithBody generates requests for BackupScroll with any type of body
func NewBackupScrollRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/backup", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewRunScrollCommandRequest generates requests for RunScrollCommand
func NewRunScrollCommandRequest(server string, id string, command string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "command", runtime.ParamLocationPath, command)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/commands/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetScrollConfigRequest generates requests for GetScrollConfig
func NewGetScrollConfigRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/config", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetScrollConsolesRequest generates requests for GetScrollConsoles
func NewGetScrollConsolesRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/consoles", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetScrollLogsRequest generates requests for GetScrollLogs
func NewGetScrollLogsRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/logs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetScrollPortsRequest generates requests for GetScrollPorts
func NewGetScrollPortsRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/ports", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetScrollProceduresRequest generates requests for GetScrollProcedures
func NewGetScrollProceduresRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/procedures", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetScrollQueueRequest generates requests for GetScrollQueue
func NewGetScrollQueueRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/queue", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRestoreScrollRequest calls the generic RestoreScroll builder with application/json body
func NewRestoreScrollRequest(server string, id string, body RestoreScrollJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRestoreScrollRequestWithBody(server, id, "application/json", bodyReader)
}

// NewRestoreScrollRequestWithBody generates requests for RestoreScroll with any type of body
func NewRestoreScrollRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/restore", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewApplyScrollRoutingRequest calls the generic ApplyScrollRouting builder with application/json body
func NewApplyScrollRoutingRequest(server string, id string, body ApplyScrollRoutingJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewApplyScrollRoutingRequestWithBody(server, id, "application/json", bodyReader)
}

// NewApplyScrollRoutingRequestWithBody generates requests for ApplyScrollRouting with any type of body
func NewApplyScrollRoutingRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/routing", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetScrollRoutingTargetsRequest generates requests for GetScrollRoutingTargets
func NewGetScrollRoutingTargetsRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/routing/targets", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStartScrollRequest generates requests for StartScroll
func NewStartScrollRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/start", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewStopScrollRequest generates requests for StopScroll
func NewStopScrollRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/scrolls/%s/stop", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetHealthAuthWithResponse request
	GetHealthAuthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthAuthResponse, error)

	// ListScrollsWithResponse request
	ListScrollsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListScrollsResponse, error)

	// CreateScrollWithBodyWithResponse request with any body
	CreateScrollWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateScrollResponse, error)

	CreateScrollWithResponse(ctx context.Context, body CreateScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateScrollResponse, error)

	// EnsureScrollWithBodyWithResponse request with any body
	EnsureScrollWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnsureScrollResponse, error)

	EnsureScrollWithResponse(ctx context.Context, body EnsureScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*EnsureScrollResponse, error)

	// DeleteScrollWithResponse request
	DeleteScrollWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteScrollResponse, error)

	// GetScrollWithResponse request
	GetScrollWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollResponse, error)

	// BackupScrollWithBodyWithResponse request with any body
	BackupScrollWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BackupScrollResponse, error)

	BackupScrollWithResponse(ctx context.Context, id string, body BackupScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*BackupScrollResponse, error)

	// RunScrollCommandWithResponse request
	RunScrollCommandWithResponse(ctx context.Context, id string, command string, reqEditors ...RequestEditorFn) (*RunScrollCommandResponse, error)

	// GetScrollConfigWithResponse request
	GetScrollConfigWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollConfigResponse, error)

	// GetScrollConsolesWithResponse request
	GetScrollConsolesWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollConsolesResponse, error)

	// GetScrollLogsWithResponse request
	GetScrollLogsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollLogsResponse, error)

	// GetScrollPortsWithResponse request
	GetScrollPortsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollPortsResponse, error)

	// GetScrollProceduresWithResponse request
	GetScrollProceduresWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollProceduresResponse, error)

	// GetScrollQueueWithResponse request
	GetScrollQueueWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollQueueResponse, error)

	// RestoreScrollWithBodyWithResponse request with any body
	RestoreScrollWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RestoreScrollResponse, error)

	RestoreScrollWithResponse(ctx context.Context, id string, body RestoreScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*RestoreScrollResponse, error)

	// ApplyScrollRoutingWithBodyWithResponse request with any body
	ApplyScrollRoutingWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ApplyScrollRoutingResponse, error)

	ApplyScrollRoutingWithResponse(ctx context.Context, id string, body ApplyScrollRoutingJSONRequestBody, reqEditors ...RequestEditorFn) (*ApplyScrollRoutingResponse, error)

	// GetScrollRoutingTargetsWithResponse request
	GetScrollRoutingTargetsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollRoutingTargetsResponse, error)

	// StartScrollWithResponse request
	StartScrollWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StartScrollResponse, error)

	// StopScrollWithResponse request
	StopScrollWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StopScrollResponse, error)
}

type GetHealthAuthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *HealthResponse
	JSON503      *HealthResponse
}

// Status returns HTTPResponse.Status
func (r GetHealthAuthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthAuthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ListScrollsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r ListScrollsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListScrollsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateScrollResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r CreateScrollResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateScrollResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EnsureScrollResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r EnsureScrollResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EnsureScrollResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteScrollResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeletedScroll
}

// Status returns HTTPResponse.Status
func (r DeleteScrollResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteScrollResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScrollResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r GetScrollResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScrollResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type BackupScrollResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r BackupScrollResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r BackupScrollResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RunScrollCommandResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r RunScrollCommandResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RunScrollCommandResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScrollConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r GetScrollConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScrollConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScrollConsolesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]interface{}
}

// Status returns HTTPResponse.Status
func (r GetScrollConsolesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScrollConsolesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScrollLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ScrollLogMap
}

// Status returns HTTPResponse.Status
func (r GetScrollLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScrollLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScrollPortsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]RuntimePortStatus
}

// Status returns HTTPResponse.Status
func (r GetScrollPortsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScrollPortsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScrollProceduresResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommandStatusMap
}

// Status returns HTTPResponse.Status
func (r GetScrollProceduresResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScrollProceduresResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScrollQueueResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CommandStatusMap
}

// Status returns HTTPResponse.Status
func (r GetScrollQueueResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScrollQueueResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type RestoreScrollResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r RestoreScrollResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RestoreScrollResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type ApplyScrollRoutingResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r ApplyScrollRoutingResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ApplyScrollRoutingResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetScrollRoutingTargetsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *[]RuntimeRoutingTarget
}

// Status returns HTTPResponse.Status
func (r GetScrollRoutingTargetsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetScrollRoutingTargetsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StartScrollResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r StartScrollResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StartScrollResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type StopScrollResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RuntimeScroll
}

// Status returns HTTPResponse.Status
func (r StopScrollResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StopScrollResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetHealthAuthWithResponse request returning *GetHealthAuthResponse
func (c *ClientWithResponses) GetHealthAuthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthAuthResponse, error) {
	rsp, err := c.GetHealthAuth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthAuthResponse(rsp)
}

// ListScrollsWithResponse request returning *ListScrollsResponse
func (c *ClientWithResponses) ListScrollsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*ListScrollsResponse, error) {
	rsp, err := c.ListScrolls(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListScrollsResponse(rsp)
}

// CreateScrollWithBodyWithResponse request with arbitrary body returning *CreateScrollResponse
func (c *ClientWithResponses) CreateScrollWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateScrollResponse, error) {
	rsp, err := c.CreateScrollWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateScrollResponse(rsp)
}

func (c *ClientWithResponses) CreateScrollWithResponse(ctx context.Context, body CreateScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateScrollResponse, error) {
	rsp, err := c.CreateScroll(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateScrollResponse(rsp)
}

// EnsureScrollWithBodyWithResponse request with arbitrary body returning *EnsureScrollResponse
func (c *ClientWithResponses) EnsureScrollWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnsureScrollResponse, error) {
	rsp, err := c.EnsureScrollWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnsureScrollResponse(rsp)
}

func (c *ClientWithResponses) EnsureScrollWithResponse(ctx context.Context, body EnsureScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*EnsureScrollResponse, error) {
	rsp, err := c.EnsureScroll(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnsureScrollResponse(rsp)
}

// DeleteScrollWithResponse request returning *DeleteScrollResponse
func (c *ClientWithResponses) DeleteScrollWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteScrollResponse, error) {
	rsp, err := c.DeleteScroll(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteScrollResponse(rsp)
}

// GetScrollWithResponse request returning *GetScrollResponse
func (c *ClientWithResponses) GetScrollWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollResponse, error) {
	rsp, err := c.GetScroll(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScrollResponse(rsp)
}

// BackupScrollWithBodyWithResponse request with arbitrary body returning *BackupScrollResponse
func (c *ClientWithResponses) BackupScrollWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*BackupScrollResponse, error) {
	rsp, err := c.BackupScrollWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBackupScrollResponse(rsp)
}

func (c *ClientWithResponses) BackupScrollWithResponse(ctx context.Context, id string, body BackupScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*BackupScrollResponse, error) {
	rsp, err := c.BackupScroll(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseBackupScrollResponse(rsp)
}

// RunScrollCommandWithResponse request returning *RunScrollCommandResponse
func (c *ClientWithResponses) RunScrollCommandWithResponse(ctx context.Context, id string, command string, reqEditors ...RequestEditorFn) (*RunScrollCommandResponse, error) {
	rsp, err := c.RunScrollCommand(ctx, id, command, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRunScrollCommandResponse(rsp)
}

// GetScrollConfigWithResponse request returning *GetScrollConfigResponse
func (c *ClientWithResponses) GetScrollConfigWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollConfigResponse, error) {
	rsp, err := c.GetScrollConfig(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScrollConfigResponse(rsp)
}

// GetScrollConsolesWithResponse request returning *GetScrollConsolesResponse
func (c *ClientWithResponses) GetScrollConsolesWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollConsolesResponse, error) {
	rsp, err := c.GetScrollConsoles(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScrollConsolesResponse(rsp)
}

// GetScrollLogsWithResponse request returning *GetScrollLogsResponse
func (c *ClientWithResponses) GetScrollLogsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollLogsResponse, error) {
	rsp, err := c.GetScrollLogs(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScrollLogsResponse(rsp)
}

// GetScrollPortsWithResponse request returning *GetScrollPortsResponse
func (c *ClientWithResponses) GetScrollPortsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollPortsResponse, error) {
	rsp, err := c.GetScrollPorts(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScrollPortsResponse(rsp)
}

// GetScrollProceduresWithResponse request returning *GetScrollProceduresResponse
func (c *ClientWithResponses) GetScrollProceduresWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollProceduresResponse, error) {
	rsp, err := c.GetScrollProcedures(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScrollProceduresResponse(rsp)
}

// GetScrollQueueWithResponse request returning *GetScrollQueueResponse
func (c *ClientWithResponses) GetScrollQueueWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollQueueResponse, error) {
	rsp, err := c.GetScrollQueue(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScrollQueueResponse(rsp)
}

// RestoreScrollWithBodyWithResponse request with arbitrary body returning *RestoreScrollResponse
func (c *ClientWithResponses) RestoreScrollWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RestoreScrollResponse, error) {
	rsp, err := c.RestoreScrollWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestoreScrollResponse(rsp)
}

func (c *ClientWithResponses) RestoreScrollWithResponse(ctx context.Context, id string, body RestoreScrollJSONRequestBody, reqEditors ...RequestEditorFn) (*RestoreScrollResponse, error) {
	rsp, err := c.RestoreScroll(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRestoreScrollResponse(rsp)
}

// ApplyScrollRoutingWithBodyWithResponse request with arbitrary body returning *ApplyScrollRoutingResponse
func (c *ClientWithResponses) ApplyScrollRoutingWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ApplyScrollRoutingResponse, error) {
	rsp, err := c.ApplyScrollRoutingWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseApplyScrollRoutingResponse(rsp)
}

func (c *ClientWithResponses) ApplyScrollRoutingWithResponse(ctx context.Context, id string, body ApplyScrollRoutingJSONRequestBody, reqEditors ...RequestEditorFn) (*ApplyScrollRoutingResponse, error) {
	rsp, err := c.ApplyScrollRouting(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseApplyScrollRoutingResponse(rsp)
}

// GetScrollRoutingTargetsWithResponse request returning *GetScrollRoutingTargetsResponse
func (c *ClientWithResponses) GetScrollRoutingTargetsWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetScrollRoutingTargetsResponse, error) {
	rsp, err := c.GetScrollRoutingTargets(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetScrollRoutingTargetsResponse(rsp)
}

// StartScrollWithResponse request returning *StartScrollResponse
func (c *ClientWithResponses) StartScrollWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StartScrollResponse, error) {
	rsp, err := c.StartScroll(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStartScrollResponse(rsp)
}

// StopScrollWithResponse request returning *StopScrollResponse
func (c *ClientWithResponses) StopScrollWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*StopScrollResponse, error) {
	rsp, err := c.StopScroll(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStopScrollResponse(rsp)
}

// ParseGetHealthAuthResponse parses an HTTP response from a GetHealthAuthWithResponse call
func ParseGetHealthAuthResponse(rsp *http.Response) (*GetHealthAuthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthAuthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 503:
		var dest HealthResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON503 = &dest

	}

	return response, nil
}

// ParseListScrollsResponse parses an HTTP response from a ListScrollsWithResponse call
func ParseListScrollsResponse(rsp *http.Response) (*ListScrollsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListScrollsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateScrollResponse parses an HTTP response from a CreateScrollWithResponse call
func ParseCreateScrollResponse(rsp *http.Response) (*CreateScrollResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateScrollResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	}

	return response, nil
}

// ParseEnsureScrollResponse parses an HTTP response from a EnsureScrollWithResponse call
func ParseEnsureScrollResponse(rsp *http.Response) (*EnsureScrollResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EnsureScrollResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteScrollResponse parses an HTTP response from a DeleteScrollWithResponse call
func ParseDeleteScrollResponse(rsp *http.Response) (*DeleteScrollResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteScrollResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeletedScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetScrollResponse parses an HTTP response from a GetScrollWithResponse call
func ParseGetScrollResponse(rsp *http.Response) (*GetScrollResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScrollResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseBackupScrollResponse parses an HTTP response from a BackupScrollWithResponse call
func ParseBackupScrollResponse(rsp *http.Response) (*BackupScrollResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &BackupScrollResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRunScrollCommandResponse parses an HTTP response from a RunScrollCommandWithResponse call
func ParseRunScrollCommandResponse(rsp *http.Response) (*RunScrollCommandResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RunScrollCommandResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetScrollConfigResponse parses an HTTP response from a GetScrollConfigWithResponse call
func ParseGetScrollConfigResponse(rsp *http.Response) (*GetScrollConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScrollConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetScrollConsolesResponse parses an HTTP response from a GetScrollConsolesWithResponse call
func ParseGetScrollConsolesResponse(rsp *http.Response) (*GetScrollConsolesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScrollConsolesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetScrollLogsResponse parses an HTTP response from a GetScrollLogsWithResponse call
func ParseGetScrollLogsResponse(rsp *http.Response) (*GetScrollLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScrollLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ScrollLogMap
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetScrollPortsResponse parses an HTTP response from a GetScrollPortsWithResponse call
func ParseGetScrollPortsResponse(rsp *http.Response) (*GetScrollPortsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScrollPortsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []RuntimePortStatus
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetScrollProceduresResponse parses an HTTP response from a GetScrollProceduresWithResponse call
func ParseGetScrollProceduresResponse(rsp *http.Response) (*GetScrollProceduresResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScrollProceduresResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommandStatusMap
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetScrollQueueResponse parses an HTTP response from a GetScrollQueueWithResponse call
func ParseGetScrollQueueResponse(rsp *http.Response) (*GetScrollQueueResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScrollQueueResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CommandStatusMap
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseRestoreScrollResponse parses an HTTP response from a RestoreScrollWithResponse call
func ParseRestoreScrollResponse(rsp *http.Response) (*RestoreScrollResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RestoreScrollResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseApplyScrollRoutingResponse parses an HTTP response from a ApplyScrollRoutingWithResponse call
func ParseApplyScrollRoutingResponse(rsp *http.Response) (*ApplyScrollRoutingResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ApplyScrollRoutingResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetScrollRoutingTargetsResponse parses an HTTP response from a GetScrollRoutingTargetsWithResponse call
func ParseGetScrollRoutingTargetsResponse(rsp *http.Response) (*GetScrollRoutingTargetsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetScrollRoutingTargetsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []RuntimeRoutingTarget
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseStartScrollResponse parses an HTTP response from a StartScrollWithResponse call
func ParseStartScrollResponse(rsp *http.Response) (*StartScrollResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StartScrollResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseStopScrollResponse parses an HTTP response from a StopScrollWithResponse call
func ParseStopScrollResponse(rsp *http.Response) (*StopScrollResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StopScrollResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RuntimeScroll
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get health status
	// (GET /api/v1/health)
	GetHealthAuth(c *fiber.Ctx) error
	// List runtime scrolls
	// (GET /api/v1/scrolls)
	ListScrolls(c *fiber.Ctx) error
	// Create runtime scroll
	// (POST /api/v1/scrolls)
	CreateScroll(c *fiber.Ctx) error
	// Ensure runtime scroll exists and optionally starts
	// (POST /api/v1/scrolls/ensure)
	EnsureScroll(c *fiber.Ctx) error
	// Delete runtime scroll
	// (DELETE /api/v1/scrolls/{id})
	DeleteScroll(c *fiber.Ctx, id string) error
	// Get runtime scroll
	// (GET /api/v1/scrolls/{id})
	GetScroll(c *fiber.Ctx, id string) error
	// Execute runtime backup
	// (POST /api/v1/scrolls/{id}/backup)
	BackupScroll(c *fiber.Ctx, id string) error
	// Run runtime scroll command
	// (POST /api/v1/scrolls/{id}/commands/{command})
	RunScrollCommand(c *fiber.Ctx, id string, command string) error
	// Get parsed scroll config
	// (GET /api/v1/scrolls/{id}/config)
	GetScrollConfig(c *fiber.Ctx, id string) error
	// Get scroll-scoped consoles
	// (GET /api/v1/scrolls/{id}/consoles)
	GetScrollConsoles(c *fiber.Ctx, id string) error
	// Get scroll-scoped logs
	// (GET /api/v1/scrolls/{id}/logs)
	GetScrollLogs(c *fiber.Ctx, id string) error
	// Get runtime scroll port status
	// (GET /api/v1/scrolls/{id}/ports)
	GetScrollPorts(c *fiber.Ctx, id string) error
	// Get procedure state
	// (GET /api/v1/scrolls/{id}/procedures)
	GetScrollProcedures(c *fiber.Ctx, id string) error
	// Get runtime queue state
	// (GET /api/v1/scrolls/{id}/queue)
	GetScrollQueue(c *fiber.Ctx, id string) error
	// Execute runtime restore
	// (POST /api/v1/scrolls/{id}/restore)
	RestoreScroll(c *fiber.Ctx, id string) error
	// Persist operator-assigned public routing
	// (POST /api/v1/scrolls/{id}/routing)
	ApplyScrollRouting(c *fiber.Ctx, id string) error
	// Get stable backend routing targets
	// (GET /api/v1/scrolls/{id}/routing/targets)
	GetScrollRoutingTargets(c *fiber.Ctx, id string) error
	// Start runtime scroll
	// (POST /api/v1/scrolls/{id}/start)
	StartScroll(c *fiber.Ctx, id string) error
	// Stop runtime scroll workloads while preserving data
	// (POST /api/v1/scrolls/{id}/stop)
	StopScroll(c *fiber.Ctx, id string) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetHealthAuth operation middleware
func (siw *ServerInterfaceWrapper) GetHealthAuth(c *fiber.Ctx) error {

	return siw.Handler.GetHealthAuth(c)
}

// ListScrolls operation middleware
func (siw *ServerInterfaceWrapper) ListScrolls(c *fiber.Ctx) error {

	return siw.Handler.ListScrolls(c)
}

// CreateScroll operation middleware
func (siw *ServerInterfaceWrapper) CreateScroll(c *fiber.Ctx) error {

	return siw.Handler.CreateScroll(c)
}

// EnsureScroll operation middleware
func (siw *ServerInterfaceWrapper) EnsureScroll(c *fiber.Ctx) error {

	return siw.Handler.EnsureScroll(c)
}

// DeleteScroll operation middleware
func (siw *ServerInterfaceWrapper) DeleteScroll(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.DeleteScroll(c, id)
}

// GetScroll operation middleware
func (siw *ServerInterfaceWrapper) GetScroll(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetScroll(c, id)
}

// BackupScroll operation middleware
func (siw *ServerInterfaceWrapper) BackupScroll(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.BackupScroll(c, id)
}

// RunScrollCommand operation middleware
func (siw *ServerInterfaceWrapper) RunScrollCommand(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	// ------------- Path parameter "command" -------------
	var command string

	err = runtime.BindStyledParameterWithOptions("simple", "command", c.Params("command"), &command, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter command: %w", err).Error())
	}

	return siw.Handler.RunScrollCommand(c, id, command)
}

// GetScrollConfig operation middleware
func (siw *ServerInterfaceWrapper) GetScrollConfig(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetScrollConfig(c, id)
}

// GetScrollConsoles operation middleware
func (siw *ServerInterfaceWrapper) GetScrollConsoles(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetScrollConsoles(c, id)
}

// GetScrollLogs operation middleware
func (siw *ServerInterfaceWrapper) GetScrollLogs(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetScrollLogs(c, id)
}

// GetScrollPorts operation middleware
func (siw *ServerInterfaceWrapper) GetScrollPorts(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetScrollPorts(c, id)
}

// GetScrollProcedures operation middleware
func (siw *ServerInterfaceWrapper) GetScrollProcedures(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetScrollProcedures(c, id)
}

// GetScrollQueue operation middleware
func (siw *ServerInterfaceWrapper) GetScrollQueue(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetScrollQueue(c, id)
}

// RestoreScroll operation middleware
func (siw *ServerInterfaceWrapper) RestoreScroll(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.RestoreScroll(c, id)
}

// ApplyScrollRouting operation middleware
func (siw *ServerInterfaceWrapper) ApplyScrollRouting(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.ApplyScrollRouting(c, id)
}

// GetScrollRoutingTargets operation middleware
func (siw *ServerInterfaceWrapper) GetScrollRoutingTargets(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.GetScrollRoutingTargets(c, id)
}

// StartScroll operation middleware
func (siw *ServerInterfaceWrapper) StartScroll(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.StartScroll(c, id)
}

// StopScroll operation middleware
func (siw *ServerInterfaceWrapper) StopScroll(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Params("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter id: %w", err).Error())
	}

	return siw.Handler.StopScroll(c, id)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/api/v1/health", wrapper.GetHealthAuth)

	router.Get(options.BaseURL+"/api/v1/scrolls", wrapper.ListScrolls)

	router.Post(options.BaseURL+"/api/v1/scrolls", wrapper.CreateScroll)

	router.Post(options.BaseURL+"/api/v1/scrolls/ensure", wrapper.EnsureScroll)

	router.Delete(options.BaseURL+"/api/v1/scrolls/:id", wrapper.DeleteScroll)

	router.Get(options.BaseURL+"/api/v1/scrolls/:id", wrapper.GetScroll)

	router.Post(options.BaseURL+"/api/v1/scrolls/:id/backup", wrapper.BackupScroll)

	router.Post(options.BaseURL+"/api/v1/scrolls/:id/commands/:command", wrapper.RunScrollCommand)

	router.Get(options.BaseURL+"/api/v1/scrolls/:id/config", wrapper.GetScrollConfig)

	router.Get(options.BaseURL+"/api/v1/scrolls/:id/consoles", wrapper.GetScrollConsoles)

	router.Get(options.BaseURL+"/api/v1/scrolls/:id/logs", wrapper.GetScrollLogs)

	router.Get(options.BaseURL+"/api/v1/scrolls/:id/ports", wrapper.GetScrollPorts)

	router.Get(options.BaseURL+"/api/v1/scrolls/:id/procedures", wrapper.GetScrollProcedures)

	router.Get(options.BaseURL+"/api/v1/scrolls/:id/queue", wrapper.GetScrollQueue)

	router.Post(options.BaseURL+"/api/v1/scrolls/:id/restore", wrapper.RestoreScroll)

	router.Post(options.BaseURL+"/api/v1/scrolls/:id/routing", wrapper.ApplyScrollRouting)

	router.Get(options.BaseURL+"/api/v1/scrolls/:id/routing/targets", wrapper.GetScrollRoutingTargets)

	router.Post(options.BaseURL+"/api/v1/scrolls/:id/start", wrapper.StartScroll)

	router.Post(options.BaseURL+"/api/v1/scrolls/:id/stop", wrapper.StopScroll)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xa3XMctw3/VzjbPp50cpP2QX1S5CZV4oxVyR0/JB4Nj8Tt0eKSFMmVdNXc/97h195+",
	"cO/Lcit58uKxjgAI/ACQAJZPBZGVkgKENcXpU2HIAirs/3umFF9eydoyUV7BXQ3Gup+Vlgq0ZeCJsDGs",
	"FFViZxYq/58/a5gXp8Wfpmvx0yh7elULyypwouGs4S9Wk8IuFRSnBdYaL4vValJouKuZBlqc/tbZ6lND",
	"K2efgXjmc1lVWNBri21tfsXKq0cps0wKzC9baltdQ06ABmzhmmjJ+bjB2rI5Jn6FgiGaKbdBcVq8P79A",
	"aRVpmIMGQQBJjbgkmCPjBSOF7aKYFPCIK8WDtYHHHFNdM3pcllMLxvp/Tt0/RaOrsZqJ0unK6FCBt6A0",
	"EGyBIswZNmguNRK4gmP0XgUUkLF4xgHp4ALE6DQQXMyRrJi1QCfILgBRDJUUqAQBGlswCAvE6HFH8c9y",
	"ZnK6OYkZeJ5Hhb+HNWYUx0tvHTKWcY6IrMCguZZVRPp4iSu+u8ZGYZJR+5d6BlqA27+h8sAm/TUYWWsC",
	"5hhdlEJqoGi2REKKoxbrDJNbENQc53aXDwL0Tc6jMVOQp0CMotoA9buT2lhZgT6aY8JEibRLJoRru5Ca",
	"/Qc7/uxeGkpmrF7eEA0UhGWY75G4kfm84d2etCldchn7FjhYoCHjhqkWEBmYYHyCu6W1Y2mQNLS4pw5z",
	"JFFATqN/CFPrfY6AgXZp8YayMnKPJO9o3vwRni8jPP8JmNvFFRglhYFhHFSSZjxyXmsNwqKF50Yh2JCn",
	"bR9F8jZnv9Ky1GDMUOxlXEEKNAFhcRn8zCWmDmGnmMfVHXBzqStsi9NiziV290eFH1lVV8Xpm5OTSVEx",
	"Ef46aVQQdTUDHdNL2xuKbca2jwsQ7bPZ0/q0a3Z0jEcuKopJIWrO3Vnfu3FHctNDlPNDxq8DXyzkSK4p",
	"bMyD1PmMqw3okazrKefltxhagrMqh8w4i+H1PjnnsDNlLCsozHHNbXE6x9zA5PmyxG3pfdtSZyYlByz2",
	"S6GIw6XU9ro5truWz2QtaG6fiQf9hqksJn5NyY6KTFgoQxTfAqgzzu7hg8bzOSNZGRwbe4OJZffMLm+w",
	"F5UN5N2P6nGNlJYEaK1H+LS0kkie9//jzWxpA1yNfkzYv32/1q21Uzjws5LsAI0W3HFxr70Sj7zdLPOB",
	"CSof8jrtY10v+FIuNthGD7QAncQIWxvfILQhYvvNySBs4dG6o4Bvis/9bnmn+M346qYAUfWMM7IhHWrN",
	"82fcJvuZKD9gXULG+t1KlX2yY5vxh+aOAQ7ESj3eDeZCso+KAX3PCIxrmAjGLNwtbm/S74MY7ijQ225D",
	"GI+V1huvGxIaabN3A018A033OklHamF/NIPWwXEba9LhcSnlyD0agvrZBxWTInScG8Jj3bMIV3j9lrAq",
	"JoWuhXBkjkoq5X8Llk+avuZTBrla0T3RzjVDTSRE3Lq2NJp3nNvZOxd9IezeyXLjGKblhbEMbADubeEz",
	"jtSa2eW1c1YsJQBr0Ge1Xaz/+jHh8vPHDx7Qdj3788cPyMpbEGFuwHxBZJdIaXnPKGiPhhPvLjUvbg3q",
	"wlrlNXP8ac+u+OuF1PbIVSEU3dWgl2kzqdFHmF1LcgsWESkEkFS6M8foiYt0V4Qt1jtjxX4B18u49BFz",
	"6TYmUtiQz6u+kW91zSg6f3eBOK4FWfhJCkUVFrgEgzwnE6CPfBdI05wKK8UZCS3FBHF2C7+L0o9bQN+D",
	"NhNEscUzbMBMvMAHmKW149+9usz6VqdRoJgUbjWodXL85vjE57ICgRUrTovv/E+utLYL79ApVmx6/2Ya",
	"ein3S7yNuhb+BDZ1JJ2uq/DCQ+V9QQNhaOq8v3yV63s7v9lfTk4SkvHGb0Ew/WzcVmlAuu3k6LWO3lVd",
	"nQOFj+2/nnz3P9z4OlwdqBb4HrPQn/l8qqsK62WEs4+jxaXxfVDwxKQIeBefHGtyU4gc0/JTF/53zNjr",
	"SPOF4O9zfsdLcDgLGGCTBhrJkC4uTv1mrmIaOxI0caWNjbvJTQaI9qS5CIcyGPuDpMtnC4TcMHvVvQHc",
	"Lb4a+OHNs6nQg38b3ChdiV3UgyE93DfDPgzJKfjBni+Esh5pD/6+kkdys8WdPHLyf/NIQK3vkWBIzyMI",
	"Hpmx4WqRcdTPl2FCZPZ21xOjq3DOu/pn6K4wOW7cpbDGFVjQbouncIfG7yzxCvW1ThfoSQu0fqH06Ss6",
	"oTv13u6EVAOuJsX3J9+PT2EjuZAWzX3H2/Va2HavPJrkj/GfwL5O5PcM/y9F3N2jX3hsuTyYurqsVuNn",
	"1w9+/Su75PnPw20z0pd2NgaYkWONCdk9FR+B1K0Ei147yOOpA58+xf+txr1/VYugc/z+/TUiYJIVQpoN",
	"X0l6/zt0rf2k/MI0v6pF/y5cI3OQ88WclaNFdHP6nge6F3gG95v1gSMusTbrTjMaPDw8VY7sUEyN5GB2",
	"QjVQvkBc9xjGDTFPhqFbWIaPwOvp4xD6gN6RIVIBRWQNygHgc1nuAPw7R/XKCorOnCuDubPpELx5wCJh",
	"Hf9MkI8jraS2O0B9KUNN/uKw3qerb31T3LuzRw6oNNx49iqvI/2gjGkiZRdnrmlfWfYMHuzlbopknccz",
	"lzmqR3EQ4Hc11LAd6395sm8QZm/YKMQpvO9aVGuY7yIo248nDcbKTVOYq0DwRyvztfvcgPPOvUxy3EG5",
	"1frqlve6f2gc52KR9vW4PvdK+qW5e6zv6fj8ErRhxsaHZFIfhffWQFF4XYB045thEITv0NtCYGr9c4Id",
	"LrXO84NXX6p0H1PsUq0EBpTwytSL4RF1fLiZfNMwHOCj5r1XPkmv3fI3Ova7Ds8YN+eHJ3qWeZ6xUm0C",
	"WqpvFmf/vmEbzlL1C+oHqW+5xNSghwXjgJQG/wJGlP4j9BY3xOc5CcSxr+NnlxdFfClVTAuHVBQ6+Kwf",
	"lAof0CsQ1n/0iDMfBP7udJSNj5o509OwP0TGasCVM8Vxa7CawT3ma27f/Q15Y1kXi7K1MmvGUJgNObNP",
	"D/zu/qGBWUt4gJnxlBkprv9CTIR3J0wKL6BpeqIAf+YMecNXakQWQG5NljF+Zx6y/lpzy45iXKQwyVmf",
	"ImEo4m14KsDZHMiS8Dx7DJ8h948uAB+wJYvkMwr3wKXykRDfeSf8HFlGxpkQ0gbU5k4cJgRMy3rcrJti",
	"9Wn13wAAAP//E5YRdaU1AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
