// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for CommandInstructionSetRun.
const (
	Always     CommandInstructionSetRun = "always"
	Once       CommandInstructionSetRun = "once"
	Persistent CommandInstructionSetRun = "persistent"
	Restart    CommandInstructionSetRun = "restart"
)

// Defines values for ConsoleType.
const (
	ConsoleTypePlugin  ConsoleType = "plugin"
	ConsoleTypeProcess ConsoleType = "process"
	ConsoleTypeTty     ConsoleType = "tty"
)

// AugmentedPort defines model for AugmentedPort.
type AugmentedPort struct {
	CheckActivity      *bool   `json:"check_activity,omitempty"`
	Description        *string `json:"description,omitempty"`
	FinishAfterCommand *string `json:"finish_after_command,omitempty"`

	// InactiveSince When the port became inactive
	InactiveSince time.Time `json:"inactive_since"`

	// InactiveSinceSec Seconds since port became inactive
	InactiveSinceSec int   `json:"inactive_since_sec"`
	Mandatory        *bool `json:"mandatory,omitempty"`

	// Name Port name/identifier
	Name string `json:"name"`

	// Open Whether the port is currently open
	Open bool `json:"open"`

	// Port Port number
	Port int `json:"port"`

	// Protocol Network protocol
	Protocol     string             `json:"protocol"`
	SleepHandler *string            `json:"sleep_handler"`
	StartDelay   *int               `json:"start_delay,omitempty"`
	Vars         *[]ColdStarterVars `json:"vars,omitempty"`
}

// ColdStarterVars defines model for ColdStarterVars.
type ColdStarterVars struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

// CommandInstructionSet defines model for CommandInstructionSet.
type CommandInstructionSet struct {
	Dependencies *[]string   `json:"dependencies,omitempty"`
	Needs        *[]string   `json:"needs,omitempty"`
	Procedures   []Procedure `json:"procedures"`

	// Run Run mode for the command
	Run *CommandInstructionSetRun `json:"run,omitempty"`
}

// CommandInstructionSetRun Run mode for the command
type CommandInstructionSetRun string

// Console defines model for Console.
type Console struct {
	// Exit Exit code if console has exited
	Exit *int `json:"exit"`

	// InputMode Input mode for the console
	InputMode string `json:"inputMode"`

	// Type Console type
	Type ConsoleType `json:"type"`
}

// ConsoleType Console type
type ConsoleType string

// ConsolesResponse defines model for ConsolesResponse.
type ConsolesResponse struct {
	Consoles map[string]Console `json:"consoles"`
}

// Cronjob defines model for Cronjob.
type Cronjob struct {
	Command string `json:"command"`
	Name    string `json:"name"`

	// Schedule Cron schedule expression
	Schedule string `json:"schedule"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Error message
	Error  string `json:"error"`
	Status string `json:"status"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	// Mode Current health status mode
	Mode string `json:"mode"`

	// Progress Progress percentage for loading operations
	Progress float32 `json:"progress"`

	// StartDate When the daemon started
	StartDate *time.Time `json:"start_date"`
}

// Port defines model for Port.
type Port struct {
	// CheckActivity Whether to monitor port activity
	CheckActivity *bool `json:"check_activity,omitempty"`

	// Description Port description
	Description *string `json:"description,omitempty"`

	// FinishAfterCommand Command to run after port is available
	FinishAfterCommand *string `json:"finish_after_command,omitempty"`

	// Mandatory Whether this port must be open for health check
	Mandatory *bool `json:"mandatory,omitempty"`

	// Name Port name/identifier
	Name string `json:"name"`

	// Port Port number
	Port int `json:"port"`

	// Protocol Network protocol
	Protocol string `json:"protocol"`

	// SleepHandler Handler to call when port becomes inactive
	SleepHandler *string `json:"sleep_handler"`

	// StartDelay Delay in seconds before starting port check
	StartDelay *int               `json:"start_delay,omitempty"`
	Vars       *[]ColdStarterVars `json:"vars,omitempty"`
}

// Procedure defines model for Procedure.
type Procedure struct {
	// Data Procedure data payload
	Data interface{} `json:"data,omitempty"`

	// Id Unique procedure identifier
	Id *string `json:"id"`

	// IgnoreFailure Whether to continue on failure
	IgnoreFailure *bool `json:"ignore_failure,omitempty"`

	// Mode Procedure execution mode
	Mode string `json:"mode"`

	// Wait Wait condition
	Wait *Procedure_Wait `json:"wait,omitempty"`
}

// ProcedureWait0 defines model for .
type ProcedureWait0 = string

// ProcedureWait1 defines model for .
type ProcedureWait1 = int

// ProcedureWait2 defines model for .
type ProcedureWait2 = bool

// Procedure_Wait Wait condition
type Procedure_Wait struct {
	union json.RawMessage
}

// Process defines model for Process.
type Process struct {
	// Name Process name/identifier
	Name string `json:"name"`

	// Type Process type
	Type string `json:"type"`
}

// ProcessMonitorMetrics defines model for ProcessMonitorMetrics.
type ProcessMonitorMetrics struct {
	// Connections Active network connections
	Connections []string `json:"connections"`

	// Cpu CPU usage percentage
	Cpu float64 `json:"cpu"`

	// Memory Memory usage in bytes
	Memory int `json:"memory"`

	// Pid Process ID
	Pid int `json:"pid"`
}

// ProcessTreeNode defines model for ProcessTreeNode.
type ProcessTreeNode struct {
	Children   *[]ProcessTreeNode `json:"children,omitempty"`
	Cmdline    *string            `json:"cmdline,omitempty"`
	CpuPercent *float64           `json:"cpu_percent,omitempty"`
	Gids       *[]int             `json:"gids,omitempty"`

	// IoCounters I/O counters
	IoCounters *string `json:"io_counters,omitempty"`

	// Memory Memory statistics
	Memory *string `json:"memory,omitempty"`

	// MemoryEx Extended memory statistics
	MemoryEx *string `json:"memory_ex,omitempty"`
	Name     *string `json:"name,omitempty"`

	// Process Process information (simplified from gopsutil)
	Process  *string `json:"process,omitempty"`
	Username *string `json:"username,omitempty"`
}

// ProcessTreeRoot defines model for ProcessTreeRoot.
type ProcessTreeRoot struct {
	Root                 ProcessTreeNode `json:"root"`
	TotalCpuPercent      float64         `json:"total_cpu_percent"`
	TotalIoCountersRead  int64           `json:"total_io_counters_read"`
	TotalIoCountersWrite int64           `json:"total_io_counters_write"`
	TotalMemoryRss       int64           `json:"total_memory_rss"`
	TotalMemorySwap      int64           `json:"total_memory_swap"`
	TotalMemoryVms       int64           `json:"total_memory_vms"`
	TotalProcessCount    int             `json:"total_process_count"`
}

// ProcessesResponse defines model for ProcessesResponse.
type ProcessesResponse struct {
	Processes map[string]Process `json:"processes"`
}

// ScrollFile Scroll configuration file structure
type ScrollFile struct {
	// AppVersion Application version (not necessarily semver)
	AppVersion *string                           `json:"app_version,omitempty"`
	Commands   *map[string]CommandInstructionSet `json:"commands,omitempty"`
	Cronjobs   *[]Cronjob                        `json:"cronjobs,omitempty"`

	// Desc Scroll description
	Desc *string `json:"desc,omitempty"`

	// Init Initialization command
	Init *string `json:"init,omitempty"`

	// KeepAlivePPM Keep alive packets per minute
	KeepAlivePPM *int `json:"keepAlivePPM,omitempty"`

	// Name Scroll name
	Name    *string                       `json:"name,omitempty"`
	Plugins *map[string]map[string]string `json:"plugins,omitempty"`
	Ports   *[]Port                       `json:"ports,omitempty"`

	// Version Scroll version (semver)
	Version *string `json:"version,omitempty"`
}

// ScrollLogStream defines model for ScrollLogStream.
type ScrollLogStream struct {
	// Key The log stream identifier
	Key string `json:"key"`

	// Log Array of log lines
	Log []string `json:"log"`
}

// StartCommandRequest defines model for StartCommandRequest.
type StartCommandRequest struct {
	// Command The command ID to execute
	Command string `json:"command"`

	// Sync Whether to run synchronously (wait for completion)
	Sync *bool `json:"sync,omitempty"`
}

// StartProcedureRequest defines model for StartProcedureRequest.
type StartProcedureRequest struct {
	// Data The data payload for the procedure
	Data string `json:"data"`

	// Dependencies List of dependency IDs this procedure depends on
	Dependencies *[]string `json:"dependencies,omitempty"`

	// Mode The procedure mode (e.g., "stdin", or plugin mode)
	Mode string `json:"mode"`

	// Process The process name to run the procedure against
	Process string `json:"process"`

	// Sync Whether to run synchronously
	Sync *bool `json:"sync,omitempty"`
}

// TokenResponse defines model for TokenResponse.
type TokenResponse struct {
	// Token The generated authentication token
	Token string `json:"token"`
}

// WatchModeRequest defines model for WatchModeRequest.
type WatchModeRequest struct {
	// BuildCommands Build commands to run before hot reload
	BuildCommands *[]string `json:"buildCommands,omitempty"`

	// HotReloadCommands Commands to run when files change
	HotReloadCommands *[]string `json:"hotReloadCommands,omitempty"`
}

// WatchModeResponse defines model for WatchModeResponse.
type WatchModeResponse struct {
	// Enabled Current watch mode state
	Enabled bool `json:"enabled"`

	// Status Result status of the operation
	Status string `json:"status"`
}

// WatchStatusResponse defines model for WatchStatusResponse.
type WatchStatusResponse struct {
	// Enabled Whether watch mode is currently enabled
	Enabled bool `json:"enabled"`

	// WatchedPaths List of currently watched file paths
	WatchedPaths []string `json:"watchedPaths"`
}

// RunCommandJSONRequestBody defines body for RunCommand for application/json ContentType.
type RunCommandJSONRequestBody = StartCommandRequest

// RunProcedureJSONRequestBody defines body for RunProcedure for application/json ContentType.
type RunProcedureJSONRequestBody = StartProcedureRequest

// EnableWatchJSONRequestBody defines body for EnableWatch for application/json ContentType.
type EnableWatchJSONRequestBody = WatchModeRequest

// AsProcedureWait0 returns the union data inside the Procedure_Wait as a ProcedureWait0
func (t Procedure_Wait) AsProcedureWait0() (ProcedureWait0, error) {
	var body ProcedureWait0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProcedureWait0 overwrites any union data inside the Procedure_Wait as the provided ProcedureWait0
func (t *Procedure_Wait) FromProcedureWait0(v ProcedureWait0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProcedureWait0 performs a merge with any union data inside the Procedure_Wait, using the provided ProcedureWait0
func (t *Procedure_Wait) MergeProcedureWait0(v ProcedureWait0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProcedureWait1 returns the union data inside the Procedure_Wait as a ProcedureWait1
func (t Procedure_Wait) AsProcedureWait1() (ProcedureWait1, error) {
	var body ProcedureWait1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProcedureWait1 overwrites any union data inside the Procedure_Wait as the provided ProcedureWait1
func (t *Procedure_Wait) FromProcedureWait1(v ProcedureWait1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProcedureWait1 performs a merge with any union data inside the Procedure_Wait, using the provided ProcedureWait1
func (t *Procedure_Wait) MergeProcedureWait1(v ProcedureWait1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsProcedureWait2 returns the union data inside the Procedure_Wait as a ProcedureWait2
func (t Procedure_Wait) AsProcedureWait2() (ProcedureWait2, error) {
	var body ProcedureWait2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromProcedureWait2 overwrites any union data inside the Procedure_Wait as the provided ProcedureWait2
func (t *Procedure_Wait) FromProcedureWait2(v ProcedureWait2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeProcedureWait2 performs a merge with any union data inside the Procedure_Wait, using the provided ProcedureWait2
func (t *Procedure_Wait) MergeProcedureWait2(v ProcedureWait2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Procedure_Wait) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Procedure_Wait) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9Q8WW/bxrp/ZcB7HpJAseycnIMDARcXrrPUbdK6tnvzkATOiPwkTT2cYWaGslVD//1i",
	"Nq4ftdhx2os+NCZn+faduktSmRdSgDA6mdwlOl1ATt0/j8t5DsJAdiaVsQ8KJQtQhoF7nS4gvb6iqWFL",
	"Zlb2iVkVkEySqZQcqEjWoyQDnSpWGCZFY4E2iom5fT9jgunFFZ0ZUFepzHMqMnQhE+4iuNJMpGCXtI5O",
	"PixAELMAUkhlyBRSmgOJm5JRMpMqpyaZJBk18Nyw3D7ccsuVhrR/0wWkUmSauCVD14WTmTAwB2WPtphR",
	"I9UAoQTNEaws4Yl9NWYZCMNmDBQGtyxAoDQxC1A1WZgmaakUCMNXxO0ZIaAUgdsYKGU+bULQwK9Q0shU",
	"8v7OX8DcSHVNqhUIApoDFFcLKjIOyh4hSs7plEMyMaoEbIehylxlwGmTog2AllQ5MWUGcvePfyiYJZPk",
	"v8a1wI+DtI9PJM8u7Img/tfuW1c3UqXoKlmvR4mCryVTkCWTj55GDaQDA3tyiopU4Nfn6g45/QNSYy/t",
	"wtFTuignPXosKS+xNx3AA5h+NQ6BU8JToY0qU8vCC0CUP4MCRAYiDX9XVO4B1qbjKBEA2Z5bCiVTyEoF",
	"uzP0LG7BzlMloi3npSC5zIDMpFeZaI5GCYgyt8Sj/IautOWf560CJ4VWEEBppg0I0yDqAAsa2OAMEFpy",
	"6JMcbhmil69vmSGphZvNSOr3kgXVxC4HC/2AKjVUhYmiNO9lhligU/uqSxcP4GiIcd0zAkbEva2pacwq",
	"CbzVlqgFL+dMbKdfOKYGegMV9TnoQgqNkDOg4f5Ns4xZYCk/a63ZbDI8Gda92zvwVhehcCop/pBTDLxh",
	"ZzhoBCxsWckxHigpSHxN4LZQoLV9NUrgluaF3ZMckmf+v2S0mxmp7htV8GJIvlZKqmFOgH2NSLZ9THLQ",
	"ms5RadOGmjKoRkTBn7UN/LBzFJZjMP8IlJvFMNA5qi4n3r2ShdtN/D1OfVqEltcYPoWSc8sWxPmGN6QA",
	"lYIwdO7VkUuaMTG3vlxRu1Y3Q50Zl9Qap5zestzq3NHh4SjJmfB/HVYgBLdee1VqNoVYGYXcSpPzU9lQ",
	"cLXFg3c4EkhUkQBjya5h6EAUJEkuBTNS+WCo2jHaHrcioVDz0Wj3wLZrGd0LC5sqBXGrq1CNLinzFETO",
	"b4WTQ2Ef0/6wvNQ2SHUhn5ObIJ6OdCj+DwtHd4kgK2X4z+F/Dh8cUNaqZdJipwCzfeSP/oVlREo5JzdW",
	"1mNsL3PQzeB+39i0fdUr+5gwQXRIJKYwkwq8Ollldtd2WPMXx7WoNlYRVj84pIaiRsxvIPY9KejKmi8X",
	"fyCq8btgX0sgVbBEWiK3lQVsLqSCqxllPIA4aBVSKQwTJRApSFyP6QRu8Wus4BbS0j6N9r4H1A3FIrgP",
	"1EVwwocgLrqEX2fJ5GPfwSN5Tj+Z/Iza1kEW6g1ZBoKq1rtYADwQjAeECG6nEMMt2gD8e2/T34NRLNVo",
	"mCcg9b6xB9CxU2kigkFprh3tkZ+kRYnY9rPfSWlDl4bTbvlKWbZse+2Ec8hRw/7ePQ+HMkGmKwMaT8Yx",
	"jYrUP32F7OnGrEWZVICMkjZh7OkbOHKpAH4JutJ11Yxnypcqds/iGiditM8zzgQeDqdFeRWIb9/vQPo5",
	"w3PTBm27ADB5lcpSGFCIgJ2OfyXVW8yNb2a1jR+ZNlawBzdfwS2WFRqbnmck3+WgwXyiqA0ELktMeKJa",
	"q/dEs7zg1iRkZKZkTuay0KVh/Cl2Z6lBDdy73ixb51IiYaAKT/cVJ2kov9pfUPy+Bu+vFNCstZkJ8++X",
	"qHr2N98o5kPunXcH5ivPnX236Rta3GffMt/vuiBAHlFMnzp2x3ERQREBA8NokC/DNMdEAId+g8nbVGco",
	"4pL7Fhqil95aaKhvwkC9SJXk/A3DqgP+nfV/MzYvfSpJZozbqFSVqfEhURsvWhRXS1AaTZGOi4Kz1J8T",
	"FpEnQhoiwIJIFeMroiFfgkKtQ8iYHlCcwaqYmGFJfQFmj5A6VGwQV2BpMEjcLQkjE1hseCqYYZSzPz0p",
	"65Jkb/81QHHM2RLOzt73z/kZoCDUviYFTa/BuFICyZkoDd6vwEPAgEszNmv5C1fC28i1oedDQVbNqd4D",
	"m6zsURG2qQ3CtEEZDrhW4luLa51tHh0cHhyioeyA/r2T8wujgOZ9Q3ENSCBwuQDC5dzqIdCcbI66uZwj",
	"qmgRJXLmjrGh0j6xbcfCWBD9NaiFsYlm0Lxz+FqCNhvrmn1Mw0ty+somZj6halfOYsG9n3OvRNC9GS25",
	"SSYzyjWMhtM+VQpiNy2UFLLUfEWe2PzM1Ues+HCwe54iqWCvvjtc+XQkqVLEQaLgCfPlop0qVxX4KinG",
	"CNHtzLTPfMe0scJQrVqR01c61IrqBN291cSZqt3zIDxDvmxC7FsJT+BgfjAinxJtMiY+JSMiFfHGwy14",
	"2uF5xsRAwRQPT6srQ7Ya+d0iHqFzyoR+JGnaLjehSuB4X+OCSdGlvAYxHGEY+xonwhwEKGogI7Q0C2s7",
	"glP2e7a2WtwqDKQP1KSL9zIblulpyXh20vDjbeh+sK+jwutIwlALW0hDFLjy0D7yt5Dm3O0avvakc6Er",
	"9NlIR5N0QYVL0fcwjpvoMtjuEHTKIRtuHtzYM7yi2LwNr0bVzY9OGxN0yU3sPMiZk/mqP9DWqzINrbdd",
	"uyUB8kGBuHAr74F61KQG6q1hhbgRo4TbA9kZNYsNBq8+K6z38W3hdt3bIdZwtaD4jIXqGtJSMbO6sAFJ",
	"0BGgCtRxaRb1X29ibvXTh8uka3F++nDpVddn2D4cMCtr1JYsc1GBi3ccidxxNckWxhQ+M7sGEe/shDwL",
	"qcxzGyZm5GsJahUvk4p8gOmFtKFjt0xmN7rFsVo8STrWhRbsZ7DEc3HuTIa6nKGptRvddkvySpUsIyfv",
	"Tl0XpDLkqhTCtTWoIZyWIl2AJjZayKmgc9BkSRWTpSbaxoVEzj4JWqchekQ4uwYypzloUDaqGznvOqUa",
	"tPU/NzANLw4+OeCZcWpSgZM0gsXk8ODo4DDO3tCCJZPkn+7RKCmiJI5TyTPfJlNj3xFyOiE1EupfsLmg",
	"3KNn9/mGQIW9VQcflYAfIPEKfZolk+SNO/qkvszPJjgldIC8OHyBFT9TKAxkLeF0ZeemWH78vP48SnSZ",
	"51StqrsaEFpK0bn2kVANgatCjxvRHo71ax/jEVrFfk6wrdHSSFLaQ/28FCdVUqS8L/pBZqsoYqGi0xCE",
	"8R/aR/s+MdiWNmBB7bptBowqYd2j+OFwuy8yMuuEDOtR8uLwaHhf6LgS2tv2ErvuB5oRFUEeJf/C1pwK",
	"A8rKnRd94hvie0nEeSlq9jWkwfOvEoR62mIOiCC8BUMo53XXsxpmaZubNvvfgomTHgnOgW8iBL1pEicB",
	"nZItLayf6cGv96Om81fUy33EK1LUWihnggNRfSN+rI0shjXsraIpzErOV8QubHTwe9S8MLJ4FV91iImI",
	"pV1OmKtQ7G1G3N4KjIhgeOCx803qjQITJhFa0xaYjPhhDgfJI0pJZ2QEkRG/YuW18Z/f8eILUEuWAilF",
	"PVWwF78stbtkjlwLjPJc43K+j5LXtQ1NbphZWPFkikSydHlptePYVVEerO87FY26RZt+PNgjdaveElC7",
	"pwlonlCT21G4Jvb4zi9Zb6S6XenCOEp0ASmbsRStKfXJ7TEPFC+oojn4XtfHvj3on+eiQxsQ1cGhvzbp",
	"etBRgzfdfOTzI2ptj8V9lr6rC3DxSudzX2I20S0T0pCZLEV2D84PswoXgrxufQ+yP6zxx3IeJ6EgI3XT",
	"ALGbsav+QPI/oOvRae8jPZAet2JvMuKc02J/W1e0D2lQPj7xxK9q0IOkb7ZI6VSWlXd3Ua3lgDsCof5Z",
	"ePH4Zq79pcc+Rs4Pq9Uo3oPS3RNqUrtppEDn1rTRllRCGyoyyqVol0p7mcNZ4+Wj5Q696u/u2cPOQOym",
	"E67ouW/uUe98SPaxfz7RqnFjGUX7o4BB9XOZZFUMs6qnSiHcnF19AKZ8zbePYv22NbgGU4yiyRJT6n1T",
	"jMq+tc/o0blRlK4pHjvZG+O7utjWIvaQmzlrvHw0P99v1Q9TuA/1/m4cw7wybG26Wu8OW6U4uiS7uHLk",
	"u9HXjbz8hV68GtvZx387PB/kvI3HGvfcX0sotxM9SHJVnaqHPP1+hNq/hRd/E6PhwKm+RLgPOSPuEeNI",
	"T/+3p2YwGUPkPAdTKqGbJOUr9/mCdUS7FPregrmIZumRcwE3I4NQMvZnArwzdp8kOm0dMuTcqpbegHD6",
	"rp4NdRoVe6xW32779ah6ooAauAzl+keja7uBiZD2bdWn9JjvRVaPRAPpqv0wUDdzvZpxxrQfIR+syBtZ",
	"+C6R22BT0S79XvkzXPPrMQnYbysiRPxQN88Cblmj7vtN4Gh/yYXAUNWT71FIDsQkGSyBy8JmJNUofeSk",
	"I3STi74Dt4mJVJk2F52KNC7pcfW1aDP122cGvfb5OmQFfxP5iX3NOrj/PuLTaVm8PHrxfUlwzBXQbEXC",
	"tz7/n7THC+1+ylMPEaB+5mQB6TVhs05bPgiH673eLKjxTXRCFZApWP0KvXDMhzfGBB7dXnamEQYlPlBh",
	"b1femdNo1cQrWrtDXVcZqZgen52S5VEySkrFk0kypgUbL48Se1U4aGAo0be8HZNDQ7EdnTaqrT6sWI/u",
	"BoualmV2t7LxMSwpr3e7MmN/b7fE5rrwvlLnvWTYnldlu8ETKkTqXUU18DzUCHWRJ7rXx6T9nej0AvHf",
	"Xl6D6yyGE+pgAYG6U6sioSvreR/B9zW0O7T34z/s0+jG0EfB0K7GAVpf+oZ9zbZ7f7Nv6BHOZpCuUo6T",
	"LTTe+rvftBynhRoxMJFyTub7ZxwLIU1jppzGsaOwj1bvtRP9G5gupLxufqXfmJkNXj6lnE9p6ldJ8T58",
	"Jj65S+7+ETzIwVRmq3Vz07ArN3BrxgWnDK+sVZ2IflIQutSyNEVp/PSCV/hkp5mAADhRkIKN4r0ZqmPb",
	"9vHxa/g1ZswqEQeRFZIJP8ta63iKgFrVDQ4+iU/i2bOTSjvI7+fvJs+ekS83ejIe3y2kNuvxjR4vj8YO",
	"v/FdOG/9P06F/vvO/W/9xR903Eo87EG/uYGiqoNEvrj1X4icGspE/Gjoyzg8jkj44yKZ/HTU5NmzT+I5",
	"ufAzC9rNqnawo5pYnkaKabv+hDOXy1Ph9hD3ExLEyObPWpAlo/2dZ0zMx4UU8+qpo+01QOGn6p/8+zB8",
	"0EuYdeJLyvVTN0a0sWUW2butZ1b/5sbuTbO+HiIjoJ7onuYVybdMde3Zt3s0lfPsqxliMUkdi3uqd4TO",
	"L9ywYNfOwvfOmjxH59wIaEOnnOlFjImPsC+WbbItFfsTMvKcnIol5SwjUpGcaW2vCbntQOswotXpHfZM",
	"QQ1gryvYSXSttT1xU62/SCtdYRJugxkN6u9HNO9lSDfHbJ3f0KiNdj2VWoFgFbPO2wa+M2a5ZU3e/pht",
	"4298xU+T48/QpBXKn9FPttvDpfecEw1fPNc/ZtI6t4kHMjq6/kaOBBHmpkMZJVK8jj/F8j15v5VF3V9p",
	"2fzDQPHkx6Jk+3dpAuHeVKr2XaiHfzDigjU/xk5gaV1dBoYy3hjxbhSOH646Vjuvwtj8rtwJnzs8vsD3",
	"iLFP0OTPdLWixjGiaUVJVlo8e/HwPoGUz8LdsavvGUVdrgrQIYj6UhnAL85ruQ8Om77P1eVjwuNmtOIE",
	"vcv73RkNSbCn9AXR7asm7n3S6t9b5u8WYv3r5X1CrL8o6vn7Bh9h8nCw9mfjj6r+N6hSTV2owUZjkVGj",
	"GrL+vwAAAP///qmwG3BUAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
