// Package devapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package devapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// Defines values for WatchModeResponseStatus.
const (
	Disabled WatchModeResponseStatus = "disabled"
	Error    WatchModeResponseStatus = "error"
	Ready    WatchModeResponseStatus = "ready"
	Starting WatchModeResponseStatus = "starting"
)

// WatchModeRequest defines model for WatchModeRequest.
type WatchModeRequest struct {
	// Command Executable followed by its arguments.
	Command []string `json:"command"`

	// WatchPaths Paths relative to the mounted runtime root.
	WatchPaths []string `json:"watch_paths"`

	// WorkingDirectory Working directory relative to the mounted runtime root.
	WorkingDirectory string `json:"working_directory"`
}

// WatchModeResponse defines model for WatchModeResponse.
type WatchModeResponse struct {
	Error  *string                 `json:"error"`
	Status WatchModeResponseStatus `json:"status"`
}

// WatchModeResponseStatus defines model for WatchModeResponse.Status.
type WatchModeResponseStatus string

// FilePath defines model for FilePath.
type FilePath = string

// GetFileParams defines parameters for GetFile.
type GetFileParams struct {
	// Path Runtime-root-relative file path, for example private/package.json.
	Path FilePath `form:"path" json:"path"`
}

// HeadFileParams defines parameters for HeadFile.
type HeadFileParams struct {
	// Path Runtime-root-relative file path, for example private/package.json.
	Path FilePath `form:"path" json:"path"`
}

// OptionsFileParams defines parameters for OptionsFile.
type OptionsFileParams struct {
	// Path Runtime-root-relative file path, for example private/package.json.
	Path FilePath `form:"path" json:"path"`
}

// PutFileTextBody defines parameters for PutFile.
type PutFileTextBody = string

// PutFileParams defines parameters for PutFile.
type PutFileParams struct {
	// Path Runtime-root-relative file path, for example private/package.json.
	Path FilePath `form:"path" json:"path"`
}

// PutFileTextRequestBody defines body for PutFile for text/plain ContentType.
type PutFileTextRequestBody = PutFileTextBody

// EnableWatchJSONRequestBody defines body for EnableWatch for application/json ContentType.
type EnableWatchJSONRequestBody = WatchModeRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetFile request
	GetFile(ctx context.Context, params *GetFileParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HeadFile request
	HeadFile(ctx context.Context, params *HeadFileParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// OptionsFile request
	OptionsFile(ctx context.Context, params *OptionsFileParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutFileWithBody request with any body
	PutFileWithBody(ctx context.Context, params *PutFileParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutFileWithTextBody(ctx context.Context, params *PutFileParams, body PutFileTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DisableWatch request
	DisableWatch(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// EnableWatchWithBody request with any body
	EnableWatchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	EnableWatch(ctx context.Context, body EnableWatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetWatchStatus request
	GetWatchStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetHealth request
	GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WatchNotifications request
	WatchNotifications(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetFile(ctx context.Context, params *GetFileParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetFileRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HeadFile(ctx context.Context, params *HeadFileParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHeadFileRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) OptionsFile(ctx context.Context, params *OptionsFileParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewOptionsFileRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutFileWithBody(ctx context.Context, params *PutFileParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutFileRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutFileWithTextBody(ctx context.Context, params *PutFileParams, body PutFileTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutFileRequestWithTextBody(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DisableWatch(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDisableWatchRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnableWatchWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnableWatchRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) EnableWatch(ctx context.Context, body EnableWatchJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewEnableWatchRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetWatchStatus(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetWatchStatusRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetHealth(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetHealthRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WatchNotifications(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWatchNotificationsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetFileRequest generates requests for GetFile
func NewGetFileRequest(server string, params *GetFileParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/files")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "path", runtime.ParamLocationQuery, params.Path); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewHeadFileRequest generates requests for HeadFile
func NewHeadFileRequest(server string, params *HeadFileParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/files")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "path", runtime.ParamLocationQuery, params.Path); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("HEAD", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewOptionsFileRequest generates requests for OptionsFile
func NewOptionsFileRequest(server string, params *OptionsFileParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/files")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "path", runtime.ParamLocationQuery, params.Path); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("OPTIONS", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutFileRequestWithTextBody calls the generic PutFile builder with text/plain body
func NewPutFileRequestWithTextBody(server string, params *PutFileParams, body PutFileTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyReader = strings.NewReader(string(body))
	return NewPutFileRequestWithBody(server, params, "text/plain", bodyReader)
}

// NewPutFileRequestWithBody generates requests for PutFile with any type of body
func NewPutFileRequestWithBody(server string, params *PutFileParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/files")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "path", runtime.ParamLocationQuery, params.Path); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDisableWatchRequest generates requests for DisableWatch
func NewDisableWatchRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/watch/disable")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewEnableWatchRequest calls the generic EnableWatch builder with application/json body
func NewEnableWatchRequest(server string, body EnableWatchJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewEnableWatchRequestWithBody(server, "application/json", bodyReader)
}

// NewEnableWatchRequestWithBody generates requests for EnableWatch with any type of body
func NewEnableWatchRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/watch/enable")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetWatchStatusRequest generates requests for GetWatchStatus
func NewGetWatchStatusRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/watch/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetHealthRequest generates requests for GetHealth
func NewGetHealthRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewWatchNotificationsRequest generates requests for WatchNotifications
func NewWatchNotificationsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/ws/v1/watch/notify")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetFileWithResponse request
	GetFileWithResponse(ctx context.Context, params *GetFileParams, reqEditors ...RequestEditorFn) (*GetFileResponse, error)

	// HeadFileWithResponse request
	HeadFileWithResponse(ctx context.Context, params *HeadFileParams, reqEditors ...RequestEditorFn) (*HeadFileResponse, error)

	// OptionsFileWithResponse request
	OptionsFileWithResponse(ctx context.Context, params *OptionsFileParams, reqEditors ...RequestEditorFn) (*OptionsFileResponse, error)

	// PutFileWithBodyWithResponse request with any body
	PutFileWithBodyWithResponse(ctx context.Context, params *PutFileParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFileResponse, error)

	PutFileWithTextBodyWithResponse(ctx context.Context, params *PutFileParams, body PutFileTextRequestBody, reqEditors ...RequestEditorFn) (*PutFileResponse, error)

	// DisableWatchWithResponse request
	DisableWatchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DisableWatchResponse, error)

	// EnableWatchWithBodyWithResponse request with any body
	EnableWatchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnableWatchResponse, error)

	EnableWatchWithResponse(ctx context.Context, body EnableWatchJSONRequestBody, reqEditors ...RequestEditorFn) (*EnableWatchResponse, error)

	// GetWatchStatusWithResponse request
	GetWatchStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWatchStatusResponse, error)

	// GetHealthWithResponse request
	GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error)

	// WatchNotificationsWithResponse request
	WatchNotificationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*WatchNotificationsResponse, error)
}

type GetFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HeadFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r HeadFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HeadFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type OptionsFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r OptionsFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r OptionsFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutFileResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PutFileResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutFileResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DisableWatchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WatchModeResponse
}

// Status returns HTTPResponse.Status
func (r DisableWatchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DisableWatchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type EnableWatchResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WatchModeResponse
}

// Status returns HTTPResponse.Status
func (r EnableWatchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r EnableWatchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetWatchStatusResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *WatchModeResponse
}

// Status returns HTTPResponse.Status
func (r GetWatchStatusResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetWatchStatusResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetHealthResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetHealthResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetHealthResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type WatchNotificationsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r WatchNotificationsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WatchNotificationsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetFileWithResponse request returning *GetFileResponse
func (c *ClientWithResponses) GetFileWithResponse(ctx context.Context, params *GetFileParams, reqEditors ...RequestEditorFn) (*GetFileResponse, error) {
	rsp, err := c.GetFile(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetFileResponse(rsp)
}

// HeadFileWithResponse request returning *HeadFileResponse
func (c *ClientWithResponses) HeadFileWithResponse(ctx context.Context, params *HeadFileParams, reqEditors ...RequestEditorFn) (*HeadFileResponse, error) {
	rsp, err := c.HeadFile(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHeadFileResponse(rsp)
}

// OptionsFileWithResponse request returning *OptionsFileResponse
func (c *ClientWithResponses) OptionsFileWithResponse(ctx context.Context, params *OptionsFileParams, reqEditors ...RequestEditorFn) (*OptionsFileResponse, error) {
	rsp, err := c.OptionsFile(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseOptionsFileResponse(rsp)
}

// PutFileWithBodyWithResponse request with arbitrary body returning *PutFileResponse
func (c *ClientWithResponses) PutFileWithBodyWithResponse(ctx context.Context, params *PutFileParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutFileResponse, error) {
	rsp, err := c.PutFileWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutFileResponse(rsp)
}

func (c *ClientWithResponses) PutFileWithTextBodyWithResponse(ctx context.Context, params *PutFileParams, body PutFileTextRequestBody, reqEditors ...RequestEditorFn) (*PutFileResponse, error) {
	rsp, err := c.PutFileWithTextBody(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutFileResponse(rsp)
}

// DisableWatchWithResponse request returning *DisableWatchResponse
func (c *ClientWithResponses) DisableWatchWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*DisableWatchResponse, error) {
	rsp, err := c.DisableWatch(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDisableWatchResponse(rsp)
}

// EnableWatchWithBodyWithResponse request with arbitrary body returning *EnableWatchResponse
func (c *ClientWithResponses) EnableWatchWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*EnableWatchResponse, error) {
	rsp, err := c.EnableWatchWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnableWatchResponse(rsp)
}

func (c *ClientWithResponses) EnableWatchWithResponse(ctx context.Context, body EnableWatchJSONRequestBody, reqEditors ...RequestEditorFn) (*EnableWatchResponse, error) {
	rsp, err := c.EnableWatch(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseEnableWatchResponse(rsp)
}

// GetWatchStatusWithResponse request returning *GetWatchStatusResponse
func (c *ClientWithResponses) GetWatchStatusWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetWatchStatusResponse, error) {
	rsp, err := c.GetWatchStatus(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetWatchStatusResponse(rsp)
}

// GetHealthWithResponse request returning *GetHealthResponse
func (c *ClientWithResponses) GetHealthWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetHealthResponse, error) {
	rsp, err := c.GetHealth(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetHealthResponse(rsp)
}

// WatchNotificationsWithResponse request returning *WatchNotificationsResponse
func (c *ClientWithResponses) WatchNotificationsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*WatchNotificationsResponse, error) {
	rsp, err := c.WatchNotifications(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWatchNotificationsResponse(rsp)
}

// ParseGetFileResponse parses an HTTP response from a GetFileWithResponse call
func ParseGetFileResponse(rsp *http.Response) (*GetFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseHeadFileResponse parses an HTTP response from a HeadFileWithResponse call
func ParseHeadFileResponse(rsp *http.Response) (*HeadFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HeadFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseOptionsFileResponse parses an HTTP response from a OptionsFileWithResponse call
func ParseOptionsFileResponse(rsp *http.Response) (*OptionsFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &OptionsFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParsePutFileResponse parses an HTTP response from a PutFileWithResponse call
func ParsePutFileResponse(rsp *http.Response) (*PutFileResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutFileResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseDisableWatchResponse parses an HTTP response from a DisableWatchWithResponse call
func ParseDisableWatchResponse(rsp *http.Response) (*DisableWatchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DisableWatchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WatchModeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseEnableWatchResponse parses an HTTP response from a EnableWatchWithResponse call
func ParseEnableWatchResponse(rsp *http.Response) (*EnableWatchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &EnableWatchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WatchModeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetWatchStatusResponse parses an HTTP response from a GetWatchStatusWithResponse call
func ParseGetWatchStatusResponse(rsp *http.Response) (*GetWatchStatusResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetWatchStatusResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest WatchModeResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetHealthResponse parses an HTTP response from a GetHealthWithResponse call
func ParseGetHealthResponse(rsp *http.Response) (*GetHealthResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetHealthResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseWatchNotificationsResponse parses an HTTP response from a WatchNotificationsWithResponse call
func ParseWatchNotificationsResponse(rsp *http.Response) (*WatchNotificationsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WatchNotificationsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Read a file from the runtime root
	// (GET /api/v1/files)
	GetFile(c *fiber.Ctx, params GetFileParams) error
	// Check if a runtime file exists
	// (HEAD /api/v1/files)
	HeadFile(c *fiber.Ctx, params HeadFileParams) error
	// Return CORS/WebDAV file access options
	// (OPTIONS /api/v1/files)
	OptionsFile(c *fiber.Ctx, params OptionsFileParams) error
	// Write a file into the runtime root
	// (PUT /api/v1/files)
	PutFile(c *fiber.Ctx, params PutFileParams) error
	// Stop the in-container build watcher
	// (POST /api/v1/watch/disable)
	DisableWatch(c *fiber.Ctx) error
	// Start or reconfigure the in-container build watcher
	// (POST /api/v1/watch/enable)
	EnableWatch(c *fiber.Ctx) error
	// Get the in-container build watcher status
	// (GET /api/v1/watch/status)
	GetWatchStatus(c *fiber.Ctx) error
	// Check dev server health
	// (GET /health)
	GetHealth(c *fiber.Ctx) error
	// Subscribe to file change and build notifications
	// (GET /ws/v1/watch/notify)
	WatchNotifications(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// GetFile operation middleware
func (siw *ServerInterfaceWrapper) GetFile(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFileParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := c.Query("path"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument path is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "path", query, &params.Path)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter path: %w", err).Error())
	}

	return siw.Handler.GetFile(c, params)
}

// HeadFile operation middleware
func (siw *ServerInterfaceWrapper) HeadFile(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params HeadFileParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := c.Query("path"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument path is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "path", query, &params.Path)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter path: %w", err).Error())
	}

	return siw.Handler.HeadFile(c, params)
}

// OptionsFile operation middleware
func (siw *ServerInterfaceWrapper) OptionsFile(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params OptionsFileParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := c.Query("path"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument path is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "path", query, &params.Path)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter path: %w", err).Error())
	}

	return siw.Handler.OptionsFile(c, params)
}

// PutFile operation middleware
func (siw *ServerInterfaceWrapper) PutFile(c *fiber.Ctx) error {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PutFileParams

	var query url.Values
	query, err = url.ParseQuery(string(c.Request().URI().QueryString()))
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for query string: %w", err).Error())
	}

	// ------------- Required query parameter "path" -------------

	if paramValue := c.Query("path"); paramValue != "" {

	} else {
		err = fmt.Errorf("Query argument path is required, but not found")
		c.Status(fiber.StatusBadRequest).JSON(err)
		return err
	}

	err = runtime.BindQueryParameter("form", true, true, "path", query, &params.Path)
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter path: %w", err).Error())
	}

	return siw.Handler.PutFile(c, params)
}

// DisableWatch operation middleware
func (siw *ServerInterfaceWrapper) DisableWatch(c *fiber.Ctx) error {

	return siw.Handler.DisableWatch(c)
}

// EnableWatch operation middleware
func (siw *ServerInterfaceWrapper) EnableWatch(c *fiber.Ctx) error {

	return siw.Handler.EnableWatch(c)
}

// GetWatchStatus operation middleware
func (siw *ServerInterfaceWrapper) GetWatchStatus(c *fiber.Ctx) error {

	return siw.Handler.GetWatchStatus(c)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(c *fiber.Ctx) error {

	return siw.Handler.GetHealth(c)
}

// WatchNotifications operation middleware
func (siw *ServerInterfaceWrapper) WatchNotifications(c *fiber.Ctx) error {

	return siw.Handler.WatchNotifications(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Get(options.BaseURL+"/api/v1/files", wrapper.GetFile)

	router.Head(options.BaseURL+"/api/v1/files", wrapper.HeadFile)

	router.Options(options.BaseURL+"/api/v1/files", wrapper.OptionsFile)

	router.Put(options.BaseURL+"/api/v1/files", wrapper.PutFile)

	router.Post(options.BaseURL+"/api/v1/watch/disable", wrapper.DisableWatch)

	router.Post(options.BaseURL+"/api/v1/watch/enable", wrapper.EnableWatch)

	router.Get(options.BaseURL+"/api/v1/watch/status", wrapper.GetWatchStatus)

	router.Get(options.BaseURL+"/health", wrapper.GetHealth)

	router.Get(options.BaseURL+"/ws/v1/watch/notify", wrapper.WatchNotifications)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xXTW/bOBP+KwTf96hEyW5OvrVNP3LYNoiBzaEICloc2WwkkhkOnRiB//tiSFm2I+Vj",
	"2yzam00OyWeeZ750LyvXemfBUpCTe+kVqhYIMP37YBo4V7Tg3xpChcaTcVZO5EW0ZFo4QOfoAKFRZJYg",
	"atOA8IoWhagdCrhTrecVNEtFUHpVXas5HH4Pzh7KQhq+6SYCrmQhrWpBTiSfloVEuIkGQcsJYYRChmoB",
	"rWIctPJsFwiNncv1es3GwTsbIGF+q/QF3EQINER9ZpeqMVpgZ7Au5GdHH1y0emjMzgvrSNRpnx/KKNIz",
	"l4qqxV9Ow85jHp0HJJOBVK5t1djF7++giqRmDYjaNY27BS1mK2EoCIXz2LIWiR6CNoy4XMjW2LO8eVxs",
	"dhWiWvHmLSP7xjyG4dusZhC9YOQELUC0LloCLTCrKljVn0Hg8NrY+TdtECpyuBriuMwmojd5MaaH+u/G",
	"ytc958eAFL0sV/1VbvYdqhQMO6LmiBqqCogO+YeNTcMabiJ0QFEgRTGfsbFlcNoEPqFl2kRiQ4avNAPL",
	"N18952F37RA+Gxpbu0eTVWhYCqYEULw5P0spmjJWVRWEUIgFqIZzV1ktEpEc/qY2leKLUkySIXZZnmI0",
	"WpzCUkwBl4CykEvAkN87Ojw+PGIKnAervJET+WdaKmQflqXyplwelwwgLcwh5RBznZ4703IiPwJxGqaD",
	"28L09V7+H6GWE/m/clu+yq1J2Reu9dWD8vDH0VFOTktg04vK+6ZzsXQVAR0EQlAt723LTu2wVSQncmas",
	"SoE0lIngjkrfKK5r90+XrJFS00EKTNxJRjnmZe9NuVPp0pGT54/01S5Vs9i27MpEXoDSQuVgqNG1KQF3",
	"E4/dVXOmXmbBrtaFXIDSQ8k+gdL/jWYjnMGdCb+EsXcLqK6FqYXqeap3AI3R5RLyMGTsS954ddJOhqR1",
	"TwkEimhhGAe8LN59uZiWlzA7ffP3boEQGw/GvPNxJH3P46ukb1LsrdOr3yFz9yeT9UtYT6F6i4YI7A/F",
	"6p5Il2gINtlqbNcun8nWddFX3FTZy64XpQbnwoh2p9kgtUT5r4ooj3f7NI552s1S5bDnjhTIZAQoAjnv",
	"B2E7JecTCcYeMCZlLKCYRdN0fSz1pw0laWWMErBPM/Le7hPykrD8YS42yr8g4n6ZFgqJtfjZgJ7yRcKh",
	"QKicrc08IryCnNv567HRInkyzWa/EasMZ5+hj0DPELI5N85LHuyeouJTtniWhccKZfepx+Po9UiFHbjL",
	"k2NIk6MwoRs8V6M9Vm8tFxuQGx+7hezkbdhqn+bW1aMOJ7I/7862Dz0/Pjoe+WiB2dRV10Ai+jkqnRuj",
	"p2FBijM+N0sfM6lOVwtl55Am66ybffD6QDa+MLmdO2bERk5kmTpiZ3u/+WbuaFgX/Uou+zsL+dr11fqf",
	"AAAA///JD7lP8Q8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
