package main

import (
	"fmt"
	"log"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"strings"

	clientcli "github.com/highcard-dev/daemon/apps/druid-client/adapters/cli"
	coldstartercli "github.com/highcard-dev/daemon/apps/druid-coldstarter/adapters/cli"
	druidcli "github.com/highcard-dev/daemon/apps/druid/adapters/cli"
	"github.com/spf13/cobra"
	"github.com/spf13/cobra/doc"
)

const cliDocsDir = "./docs_md"
const headerTemplate = `---
title: "%s"
sidebar_label: %s
---

`

var autoGeneratedFooterRegexp = regexp.MustCompile(`(?m)^###### Auto generated by spf13/cobra on .*$\n?`)
var runtimeSocketDefaultRegexp = regexp.MustCompile(`\(default "[^"]*druid-[^"]*runtime\.sock"\)`)

func main() {
	if err := clearGeneratedDocs(); err != nil {
		log.Fatal(err)
	}

	linkhandler := func(s string) string {
		return strings.TrimSuffix(s, ".md")
	}

	filePrepender := func(filename string) string {
		name := filepath.Base(filename)
		base := strings.TrimSuffix(name, path.Ext(name))
		command := strings.Split(base, "_")
		title := strings.Join(command, " ")
		sidebarLabel := title
		l := len(command)

		if l > 1 {
			matches, err := filepath.Glob(cliDocsDir + "/druid_" + command[1])
			if err != nil {
				log.Fatal(err)
			}

			if len(matches) > 2 {
				sidebarLabel = command[l-1]
			}
		}

		return fmt.Sprintf(headerTemplate, title, sidebarLabel)
	}

	roots := []*cobra.Command{
		druidcli.RootCmd,
		clientcli.NewRootCommand(),
		coldstartercli.NewRootCommand(),
	}
	for _, root := range roots {
		err := doc.GenMarkdownTreeCustom(root, cliDocsDir, filePrepender, linkhandler)
		if err != nil {
			log.Fatal(err)
		}
	}

	err := filepath.Walk(cliDocsDir, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		stat, err := os.Stat(path)
		if err != nil {
			return err
		}

		if stat.IsDir() {
			return nil
		}

		content, err := os.ReadFile(path)
		if err != nil {
			return err
		}

		normalized := normalizeGeneratedDefaults(string(content))
		newContents := autoGeneratedFooterRegexp.ReplaceAllString(normalized, "")

		err = os.WriteFile(path, []byte(newContents), 0)
		if err != nil {
			return err
		}

		return nil
	})
	if err != nil {
		log.Fatal(err)
	}
}

func normalizeGeneratedDefaults(content string) string {
	if cwd, err := os.Getwd(); err == nil {
		content = strings.ReplaceAll(content, fmt.Sprintf(`(default "%s")`, cwd), `(default ".")`)
	}
	return runtimeSocketDefaultRegexp.ReplaceAllString(content, `(default "<runtime socket>")`)
}

func clearGeneratedDocs() error {
	entries, err := os.ReadDir(cliDocsDir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".md" {
			continue
		}
		if err := os.Remove(filepath.Join(cliDocsDir, entry.Name())); err != nil {
			return err
		}
	}
	return nil
}
