// Package callbackapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package callbackapi

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
	"github.com/oapi-codegen/runtime"
)

// WorkerResult defines model for WorkerResult.
type WorkerResult struct {
	ArtifactDigest *string `json:"artifact_digest,omitempty"`
	Error          *string `json:"error,omitempty"`
	ScrollYaml     *string `json:"scroll_yaml,omitempty"`
	Token          string  `json:"token"`
}

// Runtime defines model for Runtime.
type Runtime = string

// CompleteWorkerJSONRequestBody defines body for CompleteWorker for application/json ContentType.
type CompleteWorkerJSONRequestBody = WorkerResult

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CompleteWorkerWithBody request with any body
	CompleteWorkerWithBody(ctx context.Context, runtimeId Runtime, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CompleteWorker(ctx context.Context, runtimeId Runtime, body CompleteWorkerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CompleteWorkerWithBody(ctx context.Context, runtimeId Runtime, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteWorkerRequestWithBody(c.Server, runtimeId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CompleteWorker(ctx context.Context, runtimeId Runtime, body CompleteWorkerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCompleteWorkerRequest(c.Server, runtimeId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCompleteWorkerRequest calls the generic CompleteWorker builder with application/json body
func NewCompleteWorkerRequest(server string, runtimeId Runtime, body CompleteWorkerJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCompleteWorkerRequestWithBody(server, runtimeId, "application/json", bodyReader)
}

// NewCompleteWorkerRequestWithBody generates requests for CompleteWorker with any type of body
func NewCompleteWorkerRequestWithBody(server string, runtimeId Runtime, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "runtime_id", runtime.ParamLocationPath, runtimeId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/v1/workers/%s/complete", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CompleteWorkerWithBodyWithResponse request with any body
	CompleteWorkerWithBodyWithResponse(ctx context.Context, runtimeId Runtime, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteWorkerResponse, error)

	CompleteWorkerWithResponse(ctx context.Context, runtimeId Runtime, body CompleteWorkerJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteWorkerResponse, error)
}

type CompleteWorkerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r CompleteWorkerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CompleteWorkerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CompleteWorkerWithBodyWithResponse request with arbitrary body returning *CompleteWorkerResponse
func (c *ClientWithResponses) CompleteWorkerWithBodyWithResponse(ctx context.Context, runtimeId Runtime, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CompleteWorkerResponse, error) {
	rsp, err := c.CompleteWorkerWithBody(ctx, runtimeId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteWorkerResponse(rsp)
}

func (c *ClientWithResponses) CompleteWorkerWithResponse(ctx context.Context, runtimeId Runtime, body CompleteWorkerJSONRequestBody, reqEditors ...RequestEditorFn) (*CompleteWorkerResponse, error) {
	rsp, err := c.CompleteWorker(ctx, runtimeId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCompleteWorkerResponse(rsp)
}

// ParseCompleteWorkerResponse parses an HTTP response from a CompleteWorkerWithResponse call
func ParseCompleteWorkerResponse(rsp *http.Response) (*CompleteWorkerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CompleteWorkerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Complete a pending worker action
	// (POST /internal/v1/workers/{runtime_id}/complete)
	CompleteWorker(c *fiber.Ctx, runtimeId Runtime) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// CompleteWorker operation middleware
func (siw *ServerInterfaceWrapper) CompleteWorker(c *fiber.Ctx) error {

	var err error

	// ------------- Path parameter "runtime_id" -------------
	var runtimeId Runtime

	err = runtime.BindStyledParameterWithOptions("simple", "runtime_id", c.Params("runtime_id"), &runtimeId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, fmt.Errorf("Invalid format for parameter runtime_id: %w", err).Error())
	}

	return siw.Handler.CompleteWorker(c, runtimeId)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/internal/v1/workers/:runtime_id/complete", wrapper.CompleteWorker)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/4RTsW4bMQz9FYHteIicNtNtbbpkK7J0CAyDlmhHsU5SKZ4Dw7h/LySdawc9oJtNPr53",
	"5Hs6g4lDioGCZOjPkJBxICGu/57HIG6g8tMF6CGhvEIHAUsNuHU3zkIHTL9Hx2ShFx6pg2xeacAyKadU",
	"0FnYhT1M03RpVolfkQ/Ez5RHL/UDOCZicVS7yOJ2aGRj3Z6yLNB1QMyRFzvZcPR+c8LBL/YlHigsfeLt",
	"Oi8zbN1dYHH7RkbaJi7sYmGwlA27JC6WOz0FIQ7olUHvt2gO6tvPJzVmsmp7Uu915awwWGXpqDLxkTjf",
	"QQfixBeJHzw6q/7SPN7QQAcF3YRWd/d3q7JKTBQwOejhay111at6Q+1mGn2817O2Pl/Nm3SJgCepPqfY",
	"zlxcwLLOk4UeHmdEc6uyX3PycobPTDvo4ZO+pklfIfqSo2ndLktZvkd7KjomBqFQJTEl70wV1W85Vmeu",
	"MVqSmHOkP4Ro+uhfiWMt5BRDbrH6snr417RGoriyKDSGkpAtx31YrZY8PqJ3dnZzHmvo+/+ia6RUZDWG",
	"Q4jvQaGpwPo4xmFAPt1cXaFKFKwL+8v8DO9AcF8cgFaHdXteLVDVmZE99KDr6Wfw+fKA56FpPf0JAAD/",
	"/0i8QQ4HBAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
